"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { AppShell } from "@/components/app-shell";
import { ApiError, ErrorNotice, errorValue, Field, MasterDialog, ReasonDialog, requestJson, Verification } from "@/components/master-fields";
import { useSession } from "@/components/session-provider";
import { can } from "@/lib/access";

type Uom = { id: string; code: string; name: string; dimension: string; verificationStatus: string; createdBy: string | null };
type Alias = { id: string; name: string; verificationStatus: string; createdBy: string };
type Conversion = { id: string; version: number; factor: string; effectiveFrom: string; verificationStatus: string; createdBy: string; fromUom: Uom; toUom: Uom };
type Item = { id: string; code: string; name: string; kind: string; category: string; specification: string | null; primaryUomId: string; primaryUom: Uom; version: number; active: boolean; verificationStatus: string; evidence: string | null; createdBy: string | null; updatedBy: string | null; legacyProductId: string | null; legacyMaterialId: string | null; plants: { plantId: string }[]; aliases: Alias[]; conversions: Conversion[] };
type Payload = { data: Item[]; meta: { total: number }; plants: { id: string; name: string; verificationStatus: string }[]; uoms: Uom[] };
type Reason = { title: string; endpoint: string; body: Record<string, unknown>; action: "verify" | "deactivate"; method?: string };

export default function Page() {
  const { session } = useSession();
  const [payload, setPayload] = useState<Payload | null>(null), [q, setQ] = useState(""), [page, setPage] = useState(1), [selectedId, setSelectedId] = useState("");
  const [error, setError] = useState<ApiError | null>(null), [loading, setLoading] = useState(true);
  const [editor, setEditor] = useState<{ row?: Item } | null>(null), [child, setChild] = useState<"aliases" | "conversions" | null>(null), [unitOpen, setUnitOpen] = useState(false), [reason, setReason] = useState<Reason | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { setPayload(await requestJson<Payload>(`/api/materials?q=${encodeURIComponent(q)}&page=${page}`)); } catch (error) { setError(errorValue(error)); } finally { setLoading(false); } }, [q, page]);
  useEffect(() => { const timer = setTimeout(() => void load(), 250); return () => clearTimeout(timer); }, [load]);
  const item = payload?.data.find(row => row.id === selectedId);
  const allowed = (action: string, row?: Item) => !!session && can(session, `master.material.${action}`) && (!row || (session.allPlants || row.plants.length > 0 && row.plants.every(p => can(session, `master.material.${action}`, p.plantId))));
  const saved = () => { setEditor(null); setChild(null); setUnitOpen(false); setReason(null); void load(); };
  return <AppShell active="Material & UOM"><div className="content master-page"><div className="page-head"><div><span className="eyebrow">Master Data</span><h1>Material & UOM</h1><p>Nama resmi, spesifikasi, alias dan konversi per material.</p></div><div className="master-inline-actions">{allowed("create") && <button className="btn primary" onClick={() => setEditor({})} disabled={!payload}>Material baru</button>}{allowed("create") && session?.allPlants && <button className="btn" onClick={() => setUnitOpen(true)}>UOM baru</button>}</div></div>
    <ErrorNotice error={error} /><div className="master-toolbar"><label>Cari material <input value={q} onChange={event => { setQ(event.target.value); setPage(1); }} placeholder="Kode, nama atau alias" /></label><button className="btn" onClick={() => void load()} disabled={loading}>Muat ulang</button></div>
    <div className="master-workspace"><section className="card"><div className="data-scroll"><table className="data-table master-list-table"><thead><tr><th>Material</th><th>Jenis / UOM</th><th>Verifikasi</th><th>Detail</th></tr></thead><tbody>{!loading && payload?.data.map(row => <tr key={row.id} className={selectedId === row.id ? "master-selected" : ""}><td><strong>{row.name}</strong><div>{row.code}{!row.active && " · Nonaktif"}</div></td><td>{row.kind}<div>{row.primaryUom.code}</div></td><td><Verification value={row.verificationStatus} /></td><td><button className="btn" onClick={() => setSelectedId(row.id)}>Buka</button></td></tr>)}</tbody></table></div>{loading && <p className="card-body" role="status">Memuat material...</p>}{!loading && !error && !payload?.data.length && <p className="card-body">Belum ada material yang cocok pada cakupan Anda.</p>}</section>
    <section className="card"><div className="card-body master-detail">{item ? <><div><h2>{item.name}</h2><Verification value={item.verificationStatus} /></div><dl><dt>Kode / versi</dt><dd>{item.code} / {item.version}</dd><dt>Kategori</dt><dd>{item.category}</dd><dt>Spesifikasi</dt><dd>{item.specification || "Belum tersedia"}</dd><dt>Plant</dt><dd>{item.plants.map(link => payload?.plants.find(p => p.id === link.plantId)?.name ?? "Plant di luar cakupan").join(", ") || "Belum dipetakan"}</dd><dt>Bukti</dt><dd>{item.evidence || "Belum diverifikasi"}</dd></dl>
      {(item.legacyProductId || item.legacyMaterialId) && <p className="master-note">Sumber legacy dipertahankan. Mengubah nama katalog tidak menggabungkan stok atau mengubah transaksi lama.</p>}
      <div className="master-inline-actions">{item.active && allowed("update", item) && <button className="btn" onClick={() => setEditor({ row: item })}>Ubah draft</button>}{item.active && allowed("verify", item) && item.verificationStatus !== "VERIFIED" && item.createdBy !== session?.userId && item.updatedBy !== session?.userId && <button className="btn primary" onClick={() => setReason({ title: "Verifikasi material", endpoint: `/api/materials/${item.id}`, body: { version: item.version }, action: "verify" })}>Verifikasi</button>}{item.active && allowed("deactivate", item) && <button className="btn" onClick={() => setReason({ title: "Nonaktifkan material", endpoint: `/api/materials/${item.id}`, body: { version: item.version }, action: "deactivate" })}>Nonaktifkan</button>}</div>
      <div><h3>Alias</h3><p className="master-note">Alias belum terverifikasi tidak dipakai untuk auto-mapping.</p>{item.aliases.map(alias => <div className="master-location-row" key={alias.id}><strong>{alias.name}</strong> <Verification value={alias.verificationStatus} />{alias.verificationStatus !== "VERIFIED" && allowed("verify", item) && alias.createdBy !== session?.userId && <button className="btn" onClick={() => setReason({ title: "Verifikasi alias", endpoint: `/api/materials/${item.id}/aliases`, body: { id: alias.id }, method: "POST", action: "verify" })}>Verifikasi alias</button>}</div>)}{!item.aliases.length && <p>Belum ada alias.</p>}{item.active && allowed("update", item) && <button className="btn" onClick={() => setChild("aliases")}>Tambah alias</button>}</div>
      <div><h3>Konversi / versi</h3>{item.conversions.map(conversion => <div className="master-location-row" key={conversion.id}><strong>1 {conversion.fromUom.code} = {conversion.factor} {conversion.toUom.code}</strong><p>Versi {conversion.version} · berlaku {new Date(conversion.effectiveFrom).toLocaleString("id-ID")}</p><Verification value={conversion.verificationStatus} />{conversion.verificationStatus !== "VERIFIED" && allowed("verify", item) && conversion.createdBy !== session?.userId && <button className="btn" onClick={() => setReason({ title: "Verifikasi konversi", endpoint: `/api/materials/${item.id}/conversions`, body: { id: conversion.id }, method: "POST", action: "verify" })}>Verifikasi faktor</button>}</div>)}{!item.conversions.length && <p>Belum ada konversi. Density atau kapasitas tidak diasumsikan.</p>}{item.active && allowed("update", item) && <button className="btn" onClick={() => setChild("conversions")}>Versi konversi baru</button>}</div>
    </> : <p>Pilih material untuk melihat spesifikasi, alias dan konversi.</p>}</div></section></div>
    <div className="master-pagination"><button className="btn" disabled={page <= 1 || loading} onClick={() => setPage(p => p - 1)}>Sebelumnya</button><span>Halaman {page} · {payload?.meta.total ?? 0} material</span><button className="btn" disabled={loading || page * 10 >= (payload?.meta.total ?? 0)} onClick={() => setPage(p => p + 1)}>Berikutnya</button></div>
    <section className="card" style={{ marginTop: 18 }}><div className="card-body"><h2>UOM</h2><div className="data-scroll"><table className="data-table"><thead><tr><th>Kode</th><th>Dimensi</th><th>Verifikasi</th><th>Action</th></tr></thead><tbody>{payload?.uoms.map(uom => <tr key={uom.id}><td>{uom.code} · {uom.name}</td><td>{uom.dimension}</td><td><Verification value={uom.verificationStatus} /></td><td>{allowed("verify") && session?.allPlants && uom.verificationStatus !== "VERIFIED" && uom.createdBy !== session.userId && uom.dimension !== "UNKNOWN" && <button className="btn" onClick={() => setReason({ title: "Verifikasi UOM", endpoint: `/api/uoms/${uom.id}`, body: {}, action: "verify" })}>Verifikasi</button>}</td></tr>)}</tbody></table></div></div></section>
    {payload && editor && <MaterialEditor row={editor.row} payload={payload} onClose={() => setEditor(null)} onSaved={saved} />}{payload && child && item && <ChildEditor item={item} section={child} uoms={payload.uoms} onClose={() => setChild(null)} onSaved={saved} />}{unitOpen && <UomEditor onClose={() => setUnitOpen(false)} onSaved={saved} />}{reason && <ReasonDialog {...reason} onClose={() => setReason(null)} onSaved={saved} />}
  </div></AppShell>;
}

function MaterialEditor({ row, payload, onClose, onSaved }: { row?: Item; payload: Payload; onClose: () => void; onSaved: () => void }) {
  const [plantIds, setPlantIds] = useState(row?.plants.map(p => p.plantId) ?? []), [busy, setBusy] = useState(false), [error, setError] = useState<ApiError | null>(null);
  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(null);
    const body = { code: form.get("code"), name: form.get("name"), kind: form.get("kind"), category: form.get("category"), specification: form.get("specification"), primaryUomId: form.get("primaryUomId"), plantIds, ...(row ? { version: row.version, reason: form.get("reason") } : {}) };
    try { await requestJson(row ? `/api/materials/${row.id}` : "/api/materials", body, row ? "PATCH" : "POST"); onSaved(); } catch (error) { setError(errorValue(error)); } finally { setBusy(false); }
  }
  return <MasterDialog title={row ? "Ubah draft material" : "Material baru"} onClose={onClose} busy={busy}><form onSubmit={save}><div className="card-body master-form"><ErrorNotice error={error} />
    <Field name="code" label="Kode" errors={error}><input defaultValue={row?.code} required minLength={2} maxLength={30} /></Field><Field name="name" label="Nama resmi" errors={error}><input defaultValue={row?.name} required maxLength={150} /></Field>
    <Field name="kind" label="Jenis" errors={error}><select defaultValue={row?.kind ?? "MATERIAL"}>{["MATERIAL", "PRODUCT", "SERVICE"].map(kind => <option key={kind}>{kind}</option>)}</select></Field>
    <Field name="category" label="Kategori" errors={error}><input defaultValue={row?.category} required minLength={2} maxLength={150} /></Field><Field name="specification" label="Spesifikasi / gradasi" errors={error}><textarea defaultValue={row?.specification ?? ""} maxLength={2000} rows={3} /></Field>
    <Field name="primaryUomId" label="UOM stok utama / satuan jasa" errors={error}><select defaultValue={row?.primaryUomId ?? ""} required><option value="">Pilih UOM</option>{payload.uoms.map(uom => <option key={uom.id} value={uom.id}>{uom.code} · {uom.verificationStatus === "VERIFIED" ? "Terverifikasi" : "Belum terverifikasi"}</option>)}</select></Field>
    <fieldset id="field-plantIds" className="master-checks"><legend>Plant material</legend>{payload.plants.map(plant => <label key={plant.id}><input type="checkbox" checked={plantIds.includes(plant.id)} onChange={() => setPlantIds(ids => ids.includes(plant.id) ? ids.filter(id => id !== plant.id) : [...ids, plant.id])} />{plant.name}</label>)}{!payload.plants.length && <p>Plant aktif perlu disiapkan lebih dahulu.</p>}</fieldset>
    {row && <Field name="reason" label="Alasan perubahan" errors={error}><textarea required minLength={5} maxLength={500} rows={2} /></Field>}<p className="master-note">Disimpan belum terverifikasi. Perubahan draft membatalkan verifikasi sebelumnya.</p>
  </div><div className="master-actions"><button type="button" className="btn" onClick={onClose} disabled={busy}>Batal</button><button className="btn primary" disabled={busy || !plantIds.length}>{busy ? "Menyimpan..." : "Simpan draft"}</button></div></form></MasterDialog>;
}

function ChildEditor({ item, section, uoms, onClose, onSaved }: { item: Item; section: "aliases" | "conversions"; uoms: Uom[]; onClose: () => void; onSaved: () => void }) {
  const [busy, setBusy] = useState(false), [error, setError] = useState<ApiError | null>(null);
  return <MasterDialog title={section === "aliases" ? "Alias material" : "Versi konversi baru"} onClose={onClose} busy={busy}><form onSubmit={async event => {
    event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(null);
    try { const body = section === "aliases" ? { name: form.get("name") } : { fromUomId: form.get("fromUomId"), toUomId: form.get("toUomId"), factor: form.get("factor"), effectiveFrom: new Date(String(form.get("effectiveFrom"))).toISOString() }; await requestJson(`/api/materials/${item.id}/${section}`, body); onSaved(); }
    catch (error) { setError(errorValue(error)); } finally { setBusy(false); }
  }}><div className="card-body master-form"><ErrorNotice error={error} />{section === "aliases" ? <Field name="name" label="Nama alias" errors={error}><input required minLength={2} maxLength={150} /></Field> : <>
    {["fromUomId", "toUomId"].map(name => <Field name={name} label={name === "fromUomId" ? "UOM asal" : "UOM tujuan"} errors={error} key={name}><select required defaultValue=""><option value="">Pilih UOM</option>{uoms.map(uom => <option key={uom.id} value={uom.id}>{uom.code}</option>)}</select></Field>)}
    <Field name="factor" label="Faktor: 1 UOM asal = faktor × UOM tujuan" errors={error}><input required inputMode="decimal" pattern="[0-9]+([.][0-9]+)?" placeholder="Decimal dengan titik" /></Field><Field name="effectiveFrom" label="Mulai berlaku" errors={error}><input type="datetime-local" required /></Field>
  </>}<p className="master-note">Referensi tidak aktif untuk mapping/posting sampai terverifikasi. Faktor versi lama dipertahankan.</p></div><div className="master-actions"><button type="button" className="btn" disabled={busy} onClick={onClose}>Batal</button><button className="btn primary" disabled={busy}>{busy ? "Menyimpan..." : "Simpan draft"}</button></div></form></MasterDialog>;
}

function UomEditor({ onClose, onSaved }: { onClose: () => void; onSaved: () => void }) {
  const [busy, setBusy] = useState(false), [error, setError] = useState<ApiError | null>(null);
  return <MasterDialog title="UOM baru" onClose={onClose} busy={busy}><form onSubmit={async event => { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(null); try { await requestJson("/api/uoms", { code: form.get("code"), name: form.get("name"), dimension: form.get("dimension") }); onSaved(); } catch (error) { setError(errorValue(error)); } finally { setBusy(false); } }}><div className="card-body master-form"><ErrorNotice error={error} /><Field name="code" label="Kode UOM" errors={error}><input required minLength={2} maxLength={30} /></Field><Field name="name" label="Nama UOM" errors={error}><input required minLength={2} maxLength={150} /></Field><Field name="dimension" label="Dimensi" errors={error}><select>{["MASS", "VOLUME", "COUNT", "TIME", "SERVICE"].map(dimension => <option key={dimension}>{dimension}</option>)}</select></Field><p className="master-note">UOM baru memerlukan verifikasi. Kapasitas wadah/density tetap konversi per material.</p></div><div className="master-actions"><button type="button" className="btn" disabled={busy} onClick={onClose}>Batal</button><button className="btn primary" disabled={busy}>{busy ? "Menyimpan..." : "Simpan UOM"}</button></div></form></MasterDialog>;
}
