import { after, before, describe, test } from "node:test";
import assert from "node:assert/strict";
import { randomUUID, createHash } from "node:crypto";
import { execFileSync, spawn, ChildProcess } from "node:child_process";
import { readFileSync, writeFileSync, rmSync, mkdirSync } from "node:fs";
import { createServer } from "node:net";
import { createRequire } from "node:module";
import path from "node:path";
import os from "node:os";
import { hash } from "bcryptjs";
import { PrismaClient, StageRecord, AssetDepreciation } from "@prisma/client";
import { AccessActor, allowedActions } from "../src/lib/access";
import { createConfig, actConfig } from "../src/features/stage2/configs";
import { saveRecord, actRecord } from "../src/features/stage2/documents";
import { generateDepreciation, actDepreciation } from "../src/features/stage2/depreciation";
import { saveExam, actExam, saveFollowup, actFollowup } from "../src/features/stage2/hse";
import { uploadFile, downloadFile } from "../src/features/stage2/files";
import { stageData } from "../src/features/stage2/query";
import { periodReadiness, createStockDocument, actStockDocument } from "../src/features/inventory/ledger-service";
import { trialMigration } from "../src/features/inventory/staging-trial";
import { createDepreciationCorrection, actDepreciationCorrection } from "../src/features/stage2/depreciation-correction";
import { stageExport } from "../src/features/stage2/export";
describe("Stage 2 isolated PostgreSQL", { skip: process.env.RUN_STAGE2_DB_TESTS !== "1", concurrency: false }, () => {
  const schema = `quarryflow_stage2_test_${randomUUID().replaceAll("-", "")}`, distDir = `.next-${schema}`, plants = [randomUUID(), randomUUID()], locationId = randomUUID(), evidence = "Fictional fixture evidence, not company settings";
  const date = "2026-09-15T02:00:00Z", configDate = "2026-08-01T00:00:00Z", reason = evidence;
  let admin: PrismaClient, db: PrismaClient, url: string, created = false, server: ChildProcess | undefined, tsconfig: Buffer | undefined, nextEnv: Buffer | undefined;
  let pc: AccessActor, pcPeer: AccessActor, finance: AccessActor, financePeer: AccessActor, manager: AccessActor, hse: AccessActor, hsePeer: AccessActor, technical: AccessActor, director: AccessActor;
  let typeId: string, approvalType: string, assetId: string, financeId: string, workerId: string, checklistId: string, issued: StageRecord, dep: AssetDepreciation;
  const action = (name: string, row: { version: number }) => ({ action: name, version: row.version, reason });
  const data = (workspace: string, actor: AccessActor, view = "public") => stageData(db, actor, new URL(`https://fixture.test/api/stage2?workspace=${workspace}&month=2026-09&view=${view}`));
  const letter = (configId = typeId, extra = {}) => ({ kind: "LETTER", requestKey: randomUUID(), plantId: plants[0], effectiveAt: date, configId, title: "Fixture letter", recipient: "Fixture customer", body: "Fixture actual content", fileIds: [], sources: [], ...extra });
  async function config(code: string, payload: object, maker = pc, approver = manager) {
    const row = await createConfig(db, maker, { requestKey: randomUUID(), plantId: plants[0], code, revision: 1, effectiveFrom: configDate, evidence, payload });
    if (row.kind === "ASSET_FINANCE") await actConfig(db, financePeer, row.id, { action: "attest", evidence });
    return actConfig(db, approver, row.id, { action: "verify", evidence });
  }
  before(async () => {
    if (!process.env.DATABASE_URL) process.loadEnvFile(); const connection = new URL(process.env.DATABASE_URL!); connection.searchParams.set("connection_limit", "1"); admin = new PrismaClient({ datasourceUrl: connection.toString() });
    assert.match(schema, /^quarryflow_stage2_test_[a-f0-9]{32}$/); console.info(`Owned fixture schema: ${schema}`); await admin.$executeRawUnsafe(`CREATE SCHEMA "${schema}"`); created = true;
    const target = new URL(connection); target.searchParams.set("schema", schema); target.searchParams.set("connection_limit", "5"); url = target.toString();
    execFileSync(process.execPath, ["node_modules/prisma/build/index.js", "migrate", "deploy"], { env: { ...process.env, DATABASE_URL: url, PRISMA_SCHEMA_DISABLE_ADVISORY_LOCK: "1" }, stdio: "pipe", timeout: 180000 });
    const client = new PrismaClient({ datasourceUrl: url, log: [{ emit: "event", level: "query" }] }); db = client; let qualified = false; client.$on("query", e => { if (e.query.includes(`"${schema}"."User"`)) qualified = true; }); await db.user.count(); assert.ok(qualified);
    const tables = await db.$queryRaw<{ table_schema: string }[]>`SELECT table_schema FROM information_schema.tables WHERE table_schema=${schema} AND table_name='MedicalExam'`; assert.deepEqual(tables.map(t => t.table_schema), [schema]);
    const passwordHash = await hash("Fixture-stage2-password-2026", 10);
    async function actor(role: string, functions: string[] = []): Promise<AccessActor> { const id = randomUUID(), permissions = allowedActions(role, functions), r = await db.role.findUniqueOrThrow({ where: { code: role } }); await db.user.create({ data: { id, name: `${role} stage2 fixture`, email: `${id}@example.test`, passwordHash, functions: functions as "PC"[], actionPermissions: permissions, roles: { create: { roleId: r.id } } } }); return { userId: id, roles: [role], functions, permissions, plantIds: plants, allPlants: false }; }
    pc = await actor("ADMIN", ["PC"]); pcPeer = await actor("ADMIN", ["PC"]); finance = await actor("ADMIN", ["FINANCE"]); financePeer = await actor("ADMIN", ["FINANCE"]); manager = await actor("MANAGER"); hse = await actor("HSE"); hsePeer = await actor("HSE"); technical = await actor("SUPERADMIN"); director = await actor("DIREKTUR");
    await db.plant.createMany({ data: plants.map((id, i) => ({ id, code: `S2-P${i}`, name: `Fixture plant ${i}`, kind: "SC", verificationStatus: "VERIFIED", createdBy: pc.userId, verifiedBy: manager.userId })) });
    await db.userPlantScope.createMany({ data: [pc, pcPeer, finance, financePeer, manager, hse, hsePeer, director].flatMap(a => plants.map(plantId => ({ userId: a.userId, plantId }))) });
    await db.plantLocation.create({ data: { id: locationId, code: "S2-LOC", name: "Fixture site", plantId: plants[0], kind: "WAREHOUSE", verificationStatus: "VERIFIED", createdBy: pc.userId, verifiedBy: manager.userId } });
    const type = { kind: "LETTER_TYPE", name: "Fixture letter type", displayCode: "ZZ", aliases: ["Fixture alias"], format: "{seq}/{code}/{year}", scope: "TYPE", reset: "YEAR", padding: 4, start: 1, approvalRequired: false };
    typeId = (await config("S2-LETTER", type)).id; approvalType = (await config("S2-APPROVAL", { ...type, displayCode: "YY", approvalRequired: true })).id;
    const physical = { kind: "ASSET", name: "Fixture crusher", identity: "Fixture unique crusher", plate: "", serial: "Fixture serial", chassis: "", model: "Fixture model", ownership: "OWNED", unitCount: 1, ownershipEvidence: evidence };
    assetId = (await config("S2-ASSET", physical)).rootId; await config("S2-RENT", { ...physical, name: "Fixture rental", identity: "Fixture unique rented", serial: "Fixture rent serial", ownership: "RENTED" });
    financeId = (await config("S2-FINANCE", { kind: "ASSET_FINANCE", assetId, cost: "1200", residual: "200", lifeMonths: 2, startDate: "2026-08-01", firstMonth: "FULL", openingMonth: "2026-08", openingAccumulated: "0", currency: "IDR", decimals: 2 }, finance)).id;
    workerId = (await config("S2-WORKER", { kind: "WORKER", name: "Fixture inspector", job: "Inspector", employment: "Fixture employee", active: true, userId: hse.userId }, hse)).rootId;
    checklistId = (await config("S2-CHECK", { kind: "CHECKLIST", name: "Fixture inspection", checks: [{ key: "guard", label: "Fixture actual guard" }] }, hse, hsePeer)).id;
  });
  after(async () => {
    if (server?.pid && server.exitCode === null) { if (process.platform === "win32") execFileSync("taskkill", ["/PID", String(server.pid), "/T", "/F"], { stdio: "pipe" }); else server.kill("SIGTERM"); }
    if (tsconfig) writeFileSync("tsconfig.json", tsconfig); if (nextEnv) writeFileSync("next-env.d.ts", nextEnv);
    const generated = path.resolve(distDir); assert.equal(path.dirname(generated), process.cwd()); assert.match(path.basename(generated), /^\.next-quarryflow_stage2_test_[a-f0-9]{32}$/); rmSync(generated, { recursive: true, force: true });
    await db?.$disconnect(); if (created) { assert.match(schema, /^quarryflow_stage2_test_[a-f0-9]{32}$/); await admin.$executeRawUnsafe(`DROP SCHEMA "${schema}" CASCADE`); } await admin?.$disconnect();
  });
  test("concurrent issue numbers are unique; retry and cancellation never reuse issued numbers", async () => {
    const drafts = await Promise.all(Array.from({ length: 8 }, () => saveRecord(db, pc, { payload: letter(), version: 0 }))); assert.ok(drafts.every(d => !d.number));
    const rows = await Promise.all(drafts.map(r => actRecord(db, pc, r.id, action("issue", r)))); assert.equal(new Set(rows.map(r => r.number)).size, 8); issued = rows[0];
    await Promise.all([actRecord(db, pc, drafts[0].id, action("issue", drafts[0])), actRecord(db, pc, drafts[0].id, action("issue", drafts[0]))]); assert.equal(await db.numberSequence.findFirst({ where: { documentType: { contains: "STAGE:" } } }).then(s => s!.lastNumber), 8);
    const req = await actRecord(db, pc, issued.id, action("request-cancel", issued)); const cancelled = await actRecord(db, manager, issued.id, action("cancel", req)); assert.equal(cancelled.number, issued.number);
    const next = await saveRecord(db, pc, { payload: letter(), version: 0 }), final = await actRecord(db, pc, next.id, action("issue", next)); assert.match(final.number!, /^0009\/ZZ\/2026$/);
    await assert.rejects(db.stageRecord.update({ where: { id: final.id }, data: { number: "tamper", version: { increment: 1 } } })); await assert.rejects(db.numberSequence.updateMany({ where: { documentType: { contains: "STAGE:" } }, data: { lastNumber: 1 } }));
  });
  test("approval gating, maker separation, source/config immutability and plant scope", async () => {
    const draft = await saveRecord(db, pc, { payload: letter(approvalType), version: 0 }); await assert.rejects(actRecord(db, pc, draft.id, action("issue", draft)), /persetujuan/);
    const submitted = await actRecord(db, pc, draft.id, action("submit", draft)); await assert.rejects(actRecord(db, pc, draft.id, action("verify", submitted)), /diizinkan/); const verified = await actRecord(db, manager, draft.id, action("verify", submitted)); await actRecord(db, pc, draft.id, action("issue", verified));
    await assert.rejects(db.stageConfig.update({ where: { id: typeId }, data: { code: "tamper" } })); await assert.rejects(saveRecord(db, { ...pc, plantIds: [plants[1]] }, { payload: letter(), version: 0 }), /diizinkan/); await assert.rejects(saveRecord(db, { ...technical, permissions: pc.permissions, roles: ["SUPERADMIN", "ADMIN"], functions: ["PC"] }, { payload: letter(), version: 0 }), /diizinkan/);
  });
  test("Finance params require attest and Manager; duplicate identity and rental params blocked", async () => {
    const physical = await db.stageConfig.findUniqueOrThrow({ where: { id: assetId } }); await assert.rejects(config("S2-DUP", physical.payload as object), /Identitas/);
    const rented = await db.stageConfig.findFirstOrThrow({ where: { code: "S2-RENT" } }); const param = await db.stageConfig.findUniqueOrThrow({ where: { id: financeId } }); await assert.rejects(config("S2-RENT-FIN", { ...param.payload as object, assetId: rented.rootId }, finance), /milik sendiri/);
    const row = await createConfig(db, finance, { requestKey: randomUUID(), plantId: plants[0], code: "S2-FINANCE", revision: 2, effectiveFrom: "2026-10-01T00:00:00Z", evidence, payload: { ...param.payload as object, lifeMonths: 3 } });
    await assert.rejects(actConfig(db, manager, row.id, { action: "verify", evidence }), /attest/); await assert.rejects(actConfig(db, finance, row.id, { action: "attest", evidence }), /berbeda/);
  });
  test("unique asset-period, sequential depreciation, Finance verify, residual cap and no duplicate posting", async () => {
    const generated = await Promise.all([generateDepreciation(db, finance, plants[0], "2026-08"), generateDepreciation(db, finance, plants[0], "2026-08")]); assert.equal(generated[0].rows.length, 1); assert.equal(generated[0].rows[0].id, generated[1].rows[0].id); assert.ok(generated[0].exceptions.some(e => /RENTED/.test(e.message)));
    let row = generated[0].rows[0]; await assert.rejects(actDepreciation(db, finance, row.id, action("post", row)), /status/); row = await actDepreciation(db, finance, row.id, action("submit", row)); await assert.rejects(actDepreciation(db, finance, row.id, action("verify", row)), /berbeda/); row = await actDepreciation(db, financePeer, row.id, action("verify", row));
    await Promise.all([actDepreciation(db, finance, row.id, action("post", row)), actDepreciation(db, finance, row.id, action("post", row))]); assert.equal(await db.depreciationEvent.count({ where: { sourceId: row.id } }), 1);
    dep = (await generateDepreciation(db, finance, plants[0], "2026-09")).rows[0]; const pending = await db.$transaction(tx => periodReadiness(tx, plants[0], "2026-09")); assert.ok(pending.blockers.some(b => b.domain === "DEPRECIATION"));
    const submitted = await actDepreciation(db, finance, dep.id, action("submit", dep)), verified = await actDepreciation(db, financePeer, dep.id, action("verify", submitted)); dep = await actDepreciation(db, finance, dep.id, action("post", verified)); assert.equal(dep.bookAfter.toString(), "200"); assert.equal(dep.amount.toString(), "500");
    const cap = await generateDepreciation(db, finance, plants[0], "2026-10"); assert.equal(cap.rows.length, 0); assert.ok(cap.exceptions.some(e => /residu/.test(e.message))); const assets = await data("assets", finance); assert.equal(assets.books.find(b => b.assetId === assetId)?.bookValue, "200");
    await assert.rejects(db.depreciationEvent.deleteMany({ where: { sourceId: dep.id } })); await assert.rejects(db.assetDepreciation.update({ where: { id: dep.id }, data: { amount: "1", version: { increment: 1 } } }));
  });
  test("inspection checklist, photo access, findings and independent verified follow-up", async () => {
    const file = await uploadFile(db, hse, { requestKey: randomUUID(), plantId: plants[0], domain: "INSPECTION", name: "fixture.pdf", mime: "application/pdf" }, Buffer.from("%PDF-1.7\nFixture actual evidence"));
    const p = { kind: "INSPECTION", requestKey: randomUUID(), plantId: plants[0], configId: checklistId, effectiveAt: date, locationId, inspectorId: workerId, notes: evidence, results: [{ key: "guard", result: "FAIL", detail: "Fixture guard absent" }], findings: [{ key: "guard", detail: "Fixture repair required", severity: "HIGH", picId: workerId, dueDate: "2026-09-20", fileIds: [file.id] }], fileIds: [] };
    await assert.rejects(saveRecord(db, hse, { payload: { ...p, findings: [] }, version: 0 }), /Setiap hasil gagal/);
    const draft = await saveRecord(db, hse, { payload: p, version: 0 }), sub = await actRecord(db, hse, draft.id, action("submit", draft)); await assert.rejects(actRecord(db, hse, draft.id, action("verify", sub)), /berbeda/); await actRecord(db, hsePeer, draft.id, action("verify", sub));
    const finding = await db.inspectionFinding.findFirstOrThrow({ where: { inspectionId: draft.id } }); assert.equal(finding.status, "OPEN"); const follow = await saveFollowup(db, hse, { requestKey: randomUUID(), findingId: finding.id, actualAt: date, note: "Fixture actual repair", fileIds: [] });
    await assert.rejects(actFollowup(db, hse, follow.id, action("verify", follow)), /berbeda/); assert.equal((await db.inspectionFinding.findUniqueOrThrow({ where: { id: finding.id } })).status, "OPEN"); await actFollowup(db, hsePeer, follow.id, action("verify", follow)); assert.equal((await db.inspectionFinding.findUniqueOrThrow({ where: { id: finding.id } })).status, "RESOLVED");
    assert.equal((await downloadFile(db, manager, file.id)).mime, "application/pdf"); await assert.rejects(downloadFile(db, { ...hse, plantIds: [plants[1]] }, file.id), /diizinkan/);
    await assert.rejects(db.stageFile.update({ where: { id: file.id }, data: { name: "tamper" } }));
  });
  test("medical values/files excluded from public workspace, forged grants and global audit", async () => {
    const key = randomUUID(), meta = { requestKey: key, plantId: plants[0], domain: "MEDICAL", name: "clinical.pdf", mime: "application/pdf" }, bytes = Buffer.from("%PDF-1.7\nPrivate clinical evidence"), file = await uploadFile(db, hse, meta, bytes); assert.equal((await uploadFile(db, hse, meta, bytes)).id, file.id);
    const p = { requestKey: randomUUID(), plantId: plants[0], workerId, kind: "WCU", examAt: date, validUntil: "2027-01-01T00:00:00Z", workStatus: "RESTRICTED", measurements: [{ label: "Private measurement", value: "123.45", unit: "Fixture clinical unit" }], notes: "SECRET-CLINICAL-FIXTURE", fileIds: [file.id] };
    const draft = await saveExam(db, hse, { payload: p, version: 0 }), sub = await actExam(db, hse, draft.id, action("submit", draft)); await assert.rejects(actExam(db, hse, draft.id, action("verify", sub)), /berbeda/); await actExam(db, hsePeer, draft.id, action("verify", sub));
    for (const actor of [pc, manager, director, technical]) { await assert.rejects(downloadFile(db, { ...actor, permissions: [...actor.permissions, "health.read"] }, file.id), /diizinkan/); await assert.rejects(data("inspections", { ...actor, permissions: [...actor.permissions, "health.read", "inspection.read"] }, "health"), /diizinkan/); await assert.rejects(saveExam(db, { ...actor, permissions: [...actor.permissions, "health.manage"] }, { payload: { ...p, requestKey: randomUUID() }, version: 0 }), /diizinkan/); }
    const publicData = await data("inspections", manager), health = await data("inspections", hse, "health"); assert.equal(publicData.exams.length, 0); assert.equal(publicData.summary[0].workStatus, "RESTRICTED"); assert.ok(!JSON.stringify(publicData).includes("SECRET-CLINICAL")); assert.ok(JSON.stringify(health).includes("SECRET-CLINICAL"));
    const logs = await db.auditLog.findMany({ where: { module: "HEALTH" } }); assert.ok(!JSON.stringify(logs).includes("SECRET-CLINICAL")); assert.ok(!JSON.stringify(logs).includes("123.45"));
  });
  test("read-only staging lineage, checksum, repeated trial/promotion and Excel-existing bridge", async () => {
    const uom = await db.uom.create({ data: { code: "S2-M3", name: "Fixture cubic meter", dimension: "VOLUME", verificationStatus: "VERIFIED", createdBy: pc.userId, verifiedBy: manager.userId } }), item = await db.catalogItem.create({ data: { code: "S2-RAW", name: "Fixture material", kind: "MATERIAL", category: "Fixture", primaryUomId: uom.id, verificationStatus: "VERIFIED", createdBy: pc.userId, verifiedBy: manager.userId, plants: { create: { plantId: plants[0] } } } });
    const file = Buffer.from("material,quantity,uom\nFixture material,10,M3\n"), sha256 = createHash("sha256").update(file).digest("hex"), files = new Map([["source", file]]);
    const manifest = { environment: "STAGING", batchId: randomUUID(), cutoff: "2026-09-01T00:00:00Z", ownerId: pc.userId, sources: [{ id: "source", file: "fixture.csv", sha256, workbookVersion: "FICTIONAL TEST FIXTURE" }], mappings: [{ key: "Fixture material", plantId: plants[0], itemId: item.id, locationId, uomId: uom.id, verifiedBy: manager.userId, evidence }], rows: [{ sourceId: "source", sheet: "Stock", row: 2, cells: { material: "Fixture material", quantity: "10", uom: "M3" }, mappingKey: "Fixture material", domain: "INVENTORY", quantity: "10", mode: "NEW_OPENING" }] };
    const first = await trialMigration(db, pc, manifest, files), retry = await trialMigration(db, pc, manifest, files); assert.equal(first.readyForReview, true); assert.equal(first.promotionAuthorized, false); assert.deepEqual(first.proposals, retry.proposals); assert.equal(first.rows[0].lineage, "source/Stock/2"); assert.equal(await db.stockLedgerEntry.count({ where: { itemId: item.id } }), 0);
    const proposal = first.proposals[0], draft = await createStockDocument(db, pc, proposal); await actStockDocument(db, finance, draft.id, { action: "finance", reason }); const result = await actStockDocument(db, manager, draft.id, { action: "approve", reason }); await actStockDocument(db, manager, draft.id, { action: "approve", reason }); assert.equal(await db.stockLedgerEntry.count({ where: { documentId: result.id } }), 1);
    const blocked = await trialMigration(db, pc, { ...manifest, batchId: randomUUID() }, files); assert.equal(blocked.proposals.length, 0); assert.ok(blocked.exceptions.some(e => e.code === "DOUBLE_OPENING"));
    const bridge = await trialMigration(db, pc, { ...manifest, rows: manifest.rows.map(r => ({ ...r, mode: "EXISTING_BRIDGE" })) }, files); assert.equal(bridge.readyForReview, true); assert.equal(bridge.proposals.length, 0); assert.equal(bridge.totals[0].delta, "0");
    const mismatch = await trialMigration(db, pc, { ...manifest, sources: manifest.sources.map(s => ({ ...s, sha256: "a".repeat(64) })) }, files); assert.equal(mismatch.readyForReview, false); assert.ok(mismatch.exceptions.some(e => e.code === "SOURCE_CHECKSUM"));
    if (process.env.STAGE2_SCREENSHOT_DIR) { const dir = path.resolve(process.env.STAGE2_SCREENSHOT_DIR); assert.ok(dir.startsWith(path.resolve("artifacts") + path.sep)); mkdirSync(dir, { recursive: true }); writeFileSync(path.join(dir, "staging-trial-fixture.json"), JSON.stringify({ label: "FICTIONAL FIXTURE ONLY; no company data or cut-over authorization", first, repeatedHash: retry.sourceHash, blockedDoubleOpening: blocked.exceptions, bridge: bridge.totals }, null, 2)); }
  });
  test("Complete export parity, source IDs, medical denial, stale snapshot and file attachment ACL", async () => {
    const view = await data("assets", finance), url = new URL(`https://fixture.test/api/stage2/export?workspace=assets&month=2026-09&hash=${view.snapshotHash}`), exported = await stageExport(db, finance, url); assert.equal(exported.hash, view.snapshotHash); assert.ok(exported.csv.includes("BOOK_AS_OF")); assert.ok(exported.csv.includes('"200"')); assert.ok(!exported.csv.includes("SECRET-CLINICAL"));
    url.searchParams.set("hash", "stale"); await assert.rejects(stageExport(db, finance, url), /berubah/); await assert.rejects(stageExport(db, manager, new URL("https://fixture.test/api/stage2/export?workspace=inspections&view=health")), /medis/);
    await assert.rejects(stageExport(db, { ...finance, plantIds: [plants[1]] }, new URL(`https://fixture.test/api/stage2/export?workspace=assets&month=2026-09&plantId=${plants[0]}&hash=${view.snapshotHash}`)), /diizinkan/);
  });
  test("depreciation correction is signed, Manager approved, atomic and preserves historical books", async () => {
    const payload = { requestKey: randomUUID(), targetId: dep.id, effectiveAt: "2026-10-02T00:00:00Z", amount: "-100", reason: "Fixture actual correction evidence" };
    await assert.rejects(createDepreciationCorrection(db, pc, payload), /diizinkan/);
    const a = await createDepreciationCorrection(db, finance, payload), b = await createDepreciationCorrection(db, finance, { ...payload, requestKey: randomUUID() });
    const pending = await generateDepreciation(db, finance, plants[0], "2026-10"); assert.equal(pending.rows.length, 0); assert.ok(pending.exceptions.some(e => /request koreksi/.test(e.message)));
    const sa = await actDepreciationCorrection(db, finance, a.id, action("submit", a)), sb = await actDepreciationCorrection(db, finance, b.id, action("submit", b)); await assert.rejects(actDepreciationCorrection(db, finance, a.id, action("post", sa)), /diizinkan/);
    const results = await Promise.allSettled([actDepreciationCorrection(db, manager, a.id, action("post", sa)), actDepreciationCorrection(db, manager, b.id, action("post", sb))]); assert.equal(results.filter(r => r.status === "fulfilled").length, 1);
    const win = results[0].status === "fulfilled" ? sa : sb, loser = win.id === sa.id ? sb : sa; await actDepreciationCorrection(db, manager, loser.id, action("reject", loser)); await actDepreciationCorrection(db, manager, win.id, action("post", win));
    assert.equal(await db.depreciationEvent.count({ where: { correctionId: win.id } }), 1); assert.equal((await data("assets", finance)).books.find(b => b.assetId === assetId)?.bookValue, "200");
    const october = await stageData(db, finance, new URL("https://fixture.test/api/stage2?workspace=assets&month=2026-10")); assert.equal(october.books.find(b => b.assetId === assetId)?.bookValue, "300"); assert.equal((await db.assetDepreciation.findUniqueOrThrow({ where: { id: dep.id } })).amount.toString(), "500");
    await assert.rejects(db.depreciationEvent.updateMany({ where: { correctionId: win.id }, data: { amount: "-200" } }));
    await assert.rejects(createDepreciationCorrection(db, finance, { ...payload, requestKey: randomUUID(), amount: "-501" }), /melebihi/);
  });
  test("isolated backup/restore reconciles ledger and private attachment checksums", { skip: !process.env.STAGE2_POSTGRES_BIN, timeout: 120000 }, async () => {
    const started = Date.now(), restoreName = `quarryflow_restore_test_${randomUUID().replaceAll("-", "")}`, dump = path.join(os.tmpdir(), `${restoreName}.dump`), connection = new URL(url), base = new URL(url); base.search = "";
    assert.match(restoreName, /^quarryflow_restore_test_[a-f0-9]{32}$/); assert.ok(["127.0.0.1", "localhost"].includes(base.hostname), "Restore rehearsal only uses the local test server");
    let restored: PrismaClient | undefined, dbCreated = false;
    try {
      execFileSync(path.join(process.env.STAGE2_POSTGRES_BIN!, "pg_dump.exe"), ["--dbname", base.toString(), "--schema", schema, "--format", "custom", "--file", dump], { stdio: "pipe", timeout: 60000 });
      await admin.$executeRawUnsafe(`CREATE DATABASE "${restoreName}"`); dbCreated = true; const target = new URL(base); target.pathname = `/${restoreName}`;
      execFileSync(path.join(process.env.STAGE2_POSTGRES_BIN!, "pg_restore.exe"), ["--dbname", target.toString(), "--exit-on-error", "--no-owner", dump], { stdio: "pipe", timeout: 60000 });
      target.searchParams.set("schema", schema); restored = new PrismaClient({ datasourceUrl: target.toString() });
      assert.equal(await restored.stockLedgerEntry.count(), await db.stockLedgerEntry.count()); assert.equal(await restored.depreciationEvent.count(), await db.depreciationEvent.count()); assert.equal(await restored.stageRecord.count(), await db.stageRecord.count()); assert.equal(await restored.medicalExam.count(), await db.medicalExam.count());
      const original = await db.stageFile.findMany({ select: { id: true, sha256: true } }), files = await restored.stageFile.findMany({ select: { id: true, sha256: true, content: true } }); assert.equal(files.length, original.length);
      for (const f of files) { assert.equal(createHash("sha256").update(f.content).digest("hex"), f.sha256); assert.equal(original.find(v => v.id === f.id)?.sha256, f.sha256); }
      if (process.env.STAGE2_SCREENSHOT_DIR) { const dir = path.resolve(process.env.STAGE2_SCREENSHOT_DIR); assert.ok(dir.startsWith(path.resolve("artifacts") + path.sep)); mkdirSync(dir, { recursive: true }); writeFileSync(path.join(dir, "restore-rehearsal-fixture.json"), JSON.stringify({ label: "LOCAL FICTIONAL FIXTURE REHEARSAL; not production RPO/RTO sign-off", sourceSchema: schema, ledgerCount: await restored.stockLedgerEntry.count(), depreciationEvents: await restored.depreciationEvent.count(), files: files.map(f => ({ id: f.id, sha256: f.sha256 })), elapsedMs: Date.now() - started, result: "PASS" }, null, 2)); }
    } finally { await restored?.$disconnect(); if (dbCreated) await admin.$executeRawUnsafe(`DROP DATABASE "${restoreName}"`); assert.equal(path.dirname(dump), os.tmpdir()); assert.match(path.basename(dump), /^quarryflow_restore_test_[a-f0-9]{32}\.dump$/); rmSync(dump, { force: true }); }
  });
  test("browser workflows, responsive screenshots, inspection PWA retry/conflict and medical isolation", { skip: !process.env.STAGE2_PLAYWRIGHT_MODULE, timeout: 600000 }, async () => {
    const { chromium } = createRequire(path.resolve("package.json"))(process.env.STAGE2_PLAYWRIGHT_MODULE!);
    const listener = createServer(); await new Promise<void>(r => listener.listen(0, "127.0.0.1", r)); const port = (listener.address() as { port: number }).port; await new Promise<void>(r => listener.close(() => r()));
    tsconfig = readFileSync("tsconfig.json"); nextEnv = readFileSync("next-env.d.ts");
    server = spawn(process.execPath, ["node_modules/next/dist/bin/next", "dev", "--port", String(port)], { env: { ...process.env, DATABASE_URL: url, QUARRYFLOW_TEST_DIST_DIR: distDir, NODE_ENV: "development" }, windowsHide: true, stdio: ["ignore", "pipe", "pipe"] }); let logs = ""; server.stdout?.on("data", c => { logs = (logs + c).slice(-6000); }); server.stderr?.on("data", c => { logs = (logs + c).slice(-6000); });
    const base = `http://localhost:${port}`; let ready = false; for (let i = 0; i < 120; i++) { try { if ((await fetch(`${base}/login`)).ok) { ready = true; break; } } catch {} await new Promise(r => setTimeout(r, 500)); } assert.ok(ready, logs.replace(/postgres(?:ql)?:\/\/\S+/g, "[database redacted]"));
    const browser = await chromium.launch({ channel: "chrome", headless: true });
    try {
      const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } }), page = await context.newPage(); page.setDefaultTimeout(60000); const clientErrors: string[] = []; page.on("pageerror", (error: Error) => clientErrors.push(error.message));
      const waitForShell = async () => { for (let i = 0; i < 600; i++) { if (await page.evaluate(async () => !!navigator.serviceWorker.controller && !!(await (await caches.open("quarryflow-shell-v1")).match("/inspections")))) return; await new Promise(r => setTimeout(r, 100)); } assert.fail("Inspection offline shell was not prepared"); };
      const wait = () => page.getByRole("status").filter({ hasText: "Memuat workspace" }).waitFor({ state: "detached" });
      const login = async (actor: AccessActor) => { const user = await db.user.findUniqueOrThrow({ where: { id: actor.userId } }); await page.goto(`${base}/login`); await page.getByLabel("Email *").fill(user.email); await page.getByLabel("Kata sandi *").fill("Fixture-stage2-password-2026"); await page.getByRole("button", { name: "Masuk ke StoneCrusher" }).click(); await page.waitForURL((u: URL) => u.pathname !== "/login"); };
      const shot = async (name: string) => { if (process.env.STAGE2_SCREENSHOT_DIR) { const dir = path.resolve(process.env.STAGE2_SCREENSHOT_DIR); assert.ok(dir.startsWith(path.resolve("artifacts") + path.sep)); mkdirSync(dir, { recursive: true }); await page.screenshot({ path: path.join(dir, `${name}.png`), fullPage: true }); } };
      const responsive = async () => { for (const width of [1440, 1024, 768, 390, 360]) { await page.setViewportSize({ width, height: 1000 }); assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), `overflow at ${width}`); } await page.setViewportSize({ width: 1440, height: 1000 }); };
      await login(pc); await page.goto(`${base}/documents`); await page.getByRole("heading", { name: "Surat & Document Bundle", exact: true }).waitFor(); await wait(); await responsive();
      await page.getByRole("button", { name: "Surat baru", exact: true }).click(); let dialog = page.getByRole("dialog"); await dialog.getByLabel("Plant", { exact: true }).selectOption(plants[0]); await dialog.getByLabel("Jenis surat / deret verified").selectOption(typeId); await dialog.getByLabel("Tanggal dokumen WIB").fill("2026-09-16T09:00"); await dialog.getByLabel("Judul", { exact: true }).fill("Fixture browser letter"); await dialog.getByLabel("Penerima", { exact: true }).fill("Fixture receiver"); await dialog.getByLabel("Isi dokumen", { exact: true }).fill("Fixture document actual body"); await shot("documents-composer-desktop"); await page.setViewportSize({ width: 390, height: 1000 }); await shot("documents-composer-mobile"); await page.setViewportSize({ width: 1440, height: 1000 }); await dialog.getByRole("button", { name: "Simpan draft", exact: true }).click(); await dialog.waitFor({ state: "detached" });
      await page.getByLabel("Periode WIB", { exact: true }).fill("2026-09"); await wait(); await page.getByRole("button").filter({ hasText: "Fixture browser letter" }).click(); await page.getByRole("button", { name: "Issue sesuai policy", exact: true }).click(); dialog = page.getByRole("dialog"); await dialog.getByLabel("Alasan / bukti verifikasi").fill(evidence); await dialog.getByRole("button", { name: "Proses", exact: true }).click(); await dialog.waitFor({ state: "detached" }); assert.equal((await db.stageRecord.findFirstOrThrow({ where: { payload: { path: ["title"], equals: "Fixture browser letter" } } })).status, "ISSUED");
      await login(finance); await page.goto(`${base}/assets`); await page.getByRole("heading", { name: "Aset & Depresiasi", exact: true }).waitFor(); await page.getByLabel("Periode WIB", { exact: true }).fill("2026-09"); await wait(); await page.getByRole("cell", { name: "500", exact: true }).waitFor(); await responsive(); await shot("assets-depreciation-desktop");
      await login(hse); await page.goto(`${base}/inspections`); await page.getByRole("heading", { name: "Inspeksi & Pekerja", exact: true }).waitFor(); await page.getByLabel("Periode WIB", { exact: true }).fill("2026-09"); await wait(); await responsive();
      await page.getByRole("tab", { name: "WCU / DCU berizin" }).click(); await page.getByText("SECRET-CLINICAL-FIXTURE").waitFor();
      const cached = await page.evaluate(async () => { const d = await new Promise<IDBDatabase>((resolve, reject) => { const r = indexedDB.open("quarryflow-drafts-v1"); r.onsuccess = () => resolve(r.result); r.onerror = () => reject(r.error); }); const v = await new Promise<unknown>(resolve => { const r = d.transaction("data").objectStore("data").getAll(); r.onsuccess = () => resolve(r.result); }); d.close(); return JSON.stringify(v); }); assert.ok(!cached.includes("SECRET-CLINICAL")); assert.ok(!cached.includes("health.read"));
      await page.getByRole("tab", { name: "Checklist", exact: true }).click(); await wait(); await page.getByRole("button", { name: "Inspeksi lapangan", exact: true }).click(); dialog = page.getByRole("dialog"); await dialog.getByLabel("Plant", { exact: true }).selectOption(plants[0]); await dialog.getByLabel("Versi checklist verified").selectOption(checklistId); await dialog.getByLabel("Lokasi aktual").selectOption(locationId); await dialog.getByLabel("Pemeriksa", { exact: true }).selectOption(workerId); await dialog.getByLabel("Waktu aktual WIB").fill("2026-09-16T10:00"); await dialog.getByLabel("Hasil aktual", { exact: true }).selectOption("PASS"); await dialog.getByLabel("Observasi", { exact: true }).fill("Fixture actual inspection"); await dialog.getByLabel("Catatan inspeksi", { exact: true }).fill("Fixture browser inspection offline"); await shot("inspection-checklist-desktop"); await page.setViewportSize({ width: 390, height: 1000 }); await shot("inspection-checklist-mobile"); await page.setViewportSize({ width: 1440, height: 1000 });
      await waitForShell(); const ledgerBefore = await db.stockLedgerEntry.count(); await context.setOffline(true); await dialog.getByRole("button", { name: "Simpan di perangkat", exact: true }).click(); await dialog.waitFor({ state: "detached" }); await page.getByText("UNSYNCED", { exact: false }).waitFor(); await page.reload({ waitUntil: "domcontentloaded" }); await page.getByRole("heading", { name: "Draft inspeksi perangkat", exact: true }).waitFor().catch(async () => { throw new Error(`Offline reload failed: ${await page.locator("body").innerText()} | JS errors: ${JSON.stringify(clientErrors)}`); }); await page.getByText("UNSYNCED", { exact: false }).waitFor();
      await context.setOffline(false); await wait(); const device = page.locator("section.card").filter({ has: page.getByRole("heading", { name: "Draft inspeksi perangkat", exact: true }) }); await device.getByRole("button", { name: "Sync", exact: true }).click(); await device.getByText(/^SYNCED /).waitFor();
      const synced = await db.stageRecord.findFirstOrThrow({ where: { payload: { path: ["notes"], equals: "Fixture browser inspection offline" } } }); assert.equal(synced.status, "DRAFT"); assert.equal(await db.stockLedgerEntry.count(), ledgerBefore); await device.getByRole("button", { name: "Edit", exact: true }).click(); dialog = page.getByRole("dialog"); await dialog.getByLabel("Catatan inspeksi", { exact: true }).fill("Fixture local conflict inspection"); await dialog.getByRole("button", { name: "Simpan di perangkat", exact: true }).click(); await dialog.waitFor({ state: "detached" });
      await saveRecord(db, hse, { payload: { ...synced.payload as object, notes: "Fixture server version newer" }, version: synced.version }, synced.id); await device.getByRole("button", { name: "Sync", exact: true }).click(); await device.getByText("CONFLICT", { exact: false }).waitFor(); assert.equal(await db.stageRecord.count({ where: { requestKey: synced.requestKey } }), 1); assert.equal((await db.stageRecord.findUniqueOrThrow({ where: { id: synced.id } })).version, 2);
      const cachesSafe = await page.evaluate(async () => { for (const name of await caches.keys()) { for (const r of await (await caches.open(name)).keys()) if (new URL(r.url).pathname.startsWith("/api/")) return false; } return true; }); assert.equal(cachesSafe, true);
      await login(manager); await page.goto(`${base}/inspections`); await page.getByLabel("Periode WIB", { exact: true }).fill("2026-09"); await wait(); assert.equal(await page.getByRole("tab", { name: "WCU / DCU berizin" }).count(), 0); assert.equal(await page.getByText("SECRET-CLINICAL-FIXTURE").count(), 0);
      const restricted = await context.request.get(`${base}/api/stage2?workspace=inspections&view=health&month=2026-09`); assert.equal(restricted.status(), 403);
      await login(technical); for (const route of ["documents", "assets", "inspections"]) { const r = await context.request.get(`${base}/api/stage2?workspace=${route}`); assert.equal(r.status(), 403); }
      await context.close();
    } finally { await browser.close(); }
  });
});
