"use client";
import { FormEvent, useEffect, useState } from "react";
import { AppShell } from "./app-shell";
import { ApiError, ErrorNotice, Field, MasterDialog, errorValue, requestJson } from "./master-fields";
import { useSession } from "./session-provider";
import { can } from "@/lib/access";

type Kind = "RECEIPT" | "TRANSFER" | "OPENING" | "LEGACY_IMPORT" | "OPNAME" | "ADJUSTMENT" | "INTERNAL_ISSUE" | "REVERSAL" | "PRODUCTION" | "BLENDING" | "FUEL_USAGE";
type Item = { id: string; name: string; code: string; active: boolean; verificationStatus: string; kind: string; primaryUom: { code: string; active: boolean; verificationStatus: string; dimension: string }; plants: { plantId: string }[] };
type Location = { id: string; name: string; plantId: string; active: boolean; verificationStatus: string; stockpileId: string | null; plant: { name: string; active: boolean; verificationStatus: string } };
type Line = { id?: string; itemId: string; locationId: string; destinationId?: string | null; quantity: string; bookQuantity?: string | null; itemName?: string; uomCode?: string };
type Doc = { id: string; number: string; kind: Kind; status: string; makerId: string; financeBy: string | null; effectiveAt: string; reason: string; evidence: string; sourceName?: string; checksum?: string; lines: Line[] };
type Period = { plantId: string; month: string; closed: boolean; version: number; requestedBy: string | null; financeBy: string | null; requestClose: boolean | null };
type Data = { items: Item[]; locations: Location[]; periods: Period[]; balances: { locationId: string; itemId: string; balance: string; uomId: string }[]; card: { id: string; number: string; kind: string; effectiveAt: string; quantity: string; runningBalance: string; sourceRef: string | null; evidence: string }[]; cardTotal: number; page: number; legacy: { stockpileId: string; productId: string | null; materialId: string | null; direction: string; _sum: { quantity: string | null } }[]; unmappedLegacy: number };
const labels: Record<Kind, string> = { RECEIPT: "Receipt", TRANSFER: "Transfer", OPENING: "Opening migration", LEGACY_IMPORT: "Adopsi histori legacy", OPNAME: "Opname", ADJUSTMENT: "Adjustment", INTERNAL_ISSUE: "CSR / internal issue", REVERSAL: "Reversal", PRODUCTION: "Produksi", BLENDING: "Blending", FUEL_USAGE: "Pemakaian BBM" };
const statusLabels: Record<string, string> = { SUBMITTED: "Menunggu tindakan", POSTED: "Posted", REJECTED: "Ditolak", REVERSED: "Dibalik" };
const localNow = () => new Date(Date.now() + 7 * 3600000).toISOString().slice(0, 16);
const time = (value: string) => new Date(value).toLocaleString("id-ID", { timeZone: "Asia/Jakarta" });
const emptyLine = (): Line => ({ itemId: "", locationId: "", quantity: "" });

export function InventoryWorkspace({ mode }: { mode: "inventory" | "opname" | "issue" }) {
  const { session } = useSession();
  const [data, setData] = useState<Data | null>(null), [docs, setDocs] = useState<Doc[]>([]), [selected, setSelected] = useState<Doc | null>(null);
  const [error, setError] = useState<ApiError | null>(null), [loading, setLoading] = useState(true), [kind, setKind] = useState<Kind | "">(mode === "opname" ? "OPNAME" : mode === "issue" ? "INTERNAL_ISSUE" : "");
  const [dialog, setDialog] = useState<{ kind: Kind; source?: Doc } | null>(null), [action, setAction] = useState<{ doc: Doc; action: string } | null>(null);
  const [card, setCard] = useState<{ locationId: string; itemId: string } | null>(null), [cardPage, setCardPage] = useState(1), [docPage, setDocPage] = useState(1), [docTotal, setDocTotal] = useState(0);
  const title = mode === "inventory" ? "Inventory" : mode === "opname" ? "Opname & adjustment" : "CSR / internal issue";
  const allowed = (p: string) => !!session && can(session, p);
  async function load() {
    setLoading(true); setError(null);
    try {
      const params = new URLSearchParams({ page: String(cardPage), ...(card ?? {}) });
      const [inventory, documents] = await Promise.all([requestJson<Data>(`/api/inventory?${params}`), requestJson<{ data: Doc[]; total: number }>(`/api/inventory/documents?page=${docPage}${kind ? `&kind=${kind}` : ""}`)]);
      setData(inventory); setDocs(documents.data); setDocTotal(documents.total);
      setSelected(old => documents.data.find(doc => doc.id === old?.id) ?? null);
    } catch (caught) { setError(errorValue(caught)); } finally { setLoading(false); }
  }
  useEffect(() => { void load(); }, [kind, card?.locationId, card?.itemId, cardPage, docPage]);
  const saved = () => { setDialog(null); setAction(null); void load(); };
  const locationName = (id: string) => { const l = data?.locations.find(row => row.id === id); return l ? `${l.plant.name} / ${l.name}` : id; };
  return <AppShell active={mode === "inventory" ? "Inventory" : mode === "opname" ? "Opname" : "Internal Issue"}><div className="content master-page">
    <div className="page-head"><div><span className="eyebrow">Operasional / inventory</span><h1>{title}</h1><p>{mode === "inventory" ? "Saldo per material, lokasi dan UOM. Koreksi dilakukan melalui ledger berjejak." : mode === "opname" ? "Fisik dibandingkan dengan snapshot buku pada cut-off; Manager memposting selisih." : "Pengeluaran mandiri dengan tujuan dan bukti; stock-out setelah approval Manager."}</p></div><div className="master-inline-actions">
      {allowed("inventory.adjust") && (mode === "inventory" ? ["RECEIPT", "TRANSFER"] as Kind[] : mode === "opname" ? ["OPNAME", "ADJUSTMENT"] as Kind[] : ["INTERNAL_ISSUE"] as Kind[]).map(k => <button key={k} className="btn primary" disabled={loading || !data} onClick={() => setDialog({ kind: k })}>{labels[k]} baru</button>)}
      {mode === "inventory" && allowed("inventory.migrate") && <><button className="btn" onClick={() => setDialog({ kind: "OPENING" })}>Opening migration</button><button className="btn" onClick={() => setDialog({ kind: "LEGACY_IMPORT" })}>Adopsi legacy</button></>}
    </div></div><ErrorNotice error={error} />{loading && <p role="status">Memuat inventory...</p>}<button className="btn" onClick={() => void load()} disabled={loading}>Muat ulang</button>
    {mode === "inventory" && data && <>
      <section className="card table-card"><div className="card-head"><h2>Saldo material / lokasi / UOM</h2></div><div className="data-scroll"><table className="data-table master-list-table"><thead><tr><th>Material</th><th>Plant / lokasi</th><th>UOM</th><th>Saldo ledger</th><th>Kartu stok</th></tr></thead><tbody>{data.balances.map(row => { const item = data.items.find(i => i.id === row.itemId); return <tr key={`${row.locationId}:${row.itemId}`}><td>{item?.name ?? row.itemId}</td><td>{locationName(row.locationId)}</td><td>{item?.primaryUom.code}</td><td>{row.balance}</td><td><button className="btn" onClick={() => { setCard(row); setCardPage(1); }}>Buka kartu stok</button></td></tr>; })}{!data.balances.length && <tr><td colSpan={5}>Belum ada ledger posted. Master terverifikasi diperlukan sebelum input.</td></tr>}</tbody></table></div></section>
      {card && <section className="card table-card"><div className="card-head"><h2>Kartu stok — {locationName(card.locationId)}</h2><span>{data.items.find(i => i.id === card.itemId)?.name} / {data.items.find(i => i.id === card.itemId)?.primaryUom.code}</span></div><div className="data-scroll"><table className="data-table master-list-table"><thead><tr><th>Tanggal efektif WIB</th><th>Sumber</th><th>Movement (+ masuk / − keluar)</th><th>Saldo berjalan</th><th>Bukti</th></tr></thead><tbody>{data.card.map(row => <tr key={row.id}><td>{time(row.effectiveAt)}</td><td>{row.number}<br />{labels[row.kind as Kind]}<small>{row.sourceRef}</small></td><td>{row.quantity}</td><td>{row.runningBalance}</td><td>{row.evidence}</td></tr>)}</tbody></table></div><div className="master-actions"><button className="btn" disabled={cardPage === 1} onClick={() => setCardPage(p => p - 1)}>Sebelumnya</button><span>Halaman {cardPage}</span><button className="btn" disabled={cardPage * 100 >= data.cardTotal} onClick={() => setCardPage(p => p + 1)}>Berikutnya</button></div></section>}
      {(data.legacy.length > 0 || data.unmappedLegacy > 0) && <section className="card"><div className="card-body"><h2>Histori legacy — rekonsiliasi terpisah</h2><p>Saldo legacy belum menjadi opening baru. Adopsi menyalin event asli sekali setelah sign-off PC, Finance dan Manager. Periksa nama sumber dan checksum sebelum promosi.</p><p>Movement tanpa mapping lokasi: {data.unmappedLegacy}.</p><div className="data-scroll"><table className="data-table"><thead><tr><th>Lokasi</th><th>Material legacy</th><th>Arah</th><th>Quantity sumber</th></tr></thead><tbody>{data.legacy.map((row, i) => <tr key={i}><td>{data.locations.find(l => l.stockpileId === row.stockpileId)?.name ?? row.stockpileId}</td><td>{row.productId ?? row.materialId}</td><td>{row.direction}</td><td>{row._sum.quantity}</td></tr>)}</tbody></table></div></div></section>}
    </>}
    <div className="master-toolbar"><h2>Dokumen dan approval</h2><Field name="kindFilter" label="Jenis dokumen"><select value={kind} onChange={event => { setKind(event.target.value as Kind | ""); setDocPage(1); }}><option value="">Semua jenis</option>{Object.entries(labels).filter(([k]) => mode === "inventory" || mode === "opname" && ["OPNAME", "ADJUSTMENT", "REVERSAL"].includes(k) || mode === "issue" && ["INTERNAL_ISSUE", "REVERSAL"].includes(k)).map(([value, name]) => <option value={value} key={value}>{name}</option>)}</select></Field></div>
    <div className="master-workspace"><section className="card table-card"><div className="data-scroll"><table className="data-table master-list-table"><thead><tr><th>Nomor</th><th>Jenis</th><th>Status</th><th>Efektif</th><th>Detail</th></tr></thead><tbody>{docs.map(doc => <tr key={doc.id}><td>{doc.number}</td><td>{labels[doc.kind]}</td><td>{statusLabels[doc.status]}</td><td>{time(doc.effectiveAt)}</td><td><button className="btn" onClick={() => setSelected(doc)}>Buka</button></td></tr>)}{!docs.length && <tr><td colSpan={5}>Belum ada dokumen pada filter ini.</td></tr>}</tbody></table></div><div className="master-actions"><button className="btn" disabled={docPage === 1} onClick={() => setDocPage(p => p - 1)}>Sebelumnya</button><span>Halaman {docPage}</span><button className="btn" disabled={docPage * 30 >= docTotal} onClick={() => setDocPage(p => p + 1)}>Berikutnya</button></div></section>
      <section className="card"><div className="card-body master-detail">{selected ? <><h2>{selected.number}</h2><p>{statusLabels[selected.status]} · {labels[selected.kind]}</p><p>Alasan / tujuan: {selected.reason}</p><p>Bukti: {selected.evidence}</p>{selected.sourceName && <p>Sumber: {selected.sourceName}{selected.checksum && <><br />SHA-256: {selected.checksum}</>}</p>}<div className="data-scroll"><table className="data-table"><thead><tr><th>Material / UOM</th><th>Lokasi</th>{selected.kind === "OPNAME" && <th>Buku cut-off</th>}<th>{selected.kind === "OPNAME" ? "Fisik" : "Quantity"}</th></tr></thead><tbody>{selected.lines.map((line, i) => <tr key={i}><td>{line.itemName} / {line.uomCode}</td><td>{locationName(line.locationId)}{line.destinationId && <> → {locationName(line.destinationId)}</>}</td>{selected.kind === "OPNAME" && <td>{line.bookQuantity}</td>}<td>{line.quantity}</td></tr>)}</tbody></table></div><div className="master-inline-actions">
        {selected.status === "SUBMITTED" && <>
          {allowed("inventory.adjust") && ["RECEIPT", "TRANSFER"].includes(selected.kind) && <button className="btn primary" onClick={() => setAction({ doc: selected, action: "post" })}>Post ke ledger</button>}
          {allowed("inventory.migration.verify") && ["OPENING", "LEGACY_IMPORT"].includes(selected.kind) && !selected.financeBy && selected.makerId !== session?.userId && <button className="btn" onClick={() => setAction({ doc: selected, action: "finance" })}>Verifikasi Finance</button>}
          {allowed("inventory.approve") && !["RECEIPT", "TRANSFER"].includes(selected.kind) && selected.makerId !== session?.userId && selected.financeBy !== session?.userId && <button className="btn primary" onClick={() => setAction({ doc: selected, action: "approve" })}>Approve & post</button>}
          {allowed("inventory.approve") && selected.makerId !== session?.userId && <button className="btn" onClick={() => setAction({ doc: selected, action: "reject" })}>Tolak</button>}
        </>}
        {selected.status === "POSTED" && allowed("inventory.adjust") && !["OPENING", "LEGACY_IMPORT", "REVERSAL"].includes(selected.kind) && <button className="btn" onClick={() => setDialog({ kind: "REVERSAL", source: selected })}>Ajukan reversal</button>}
      </div></> : <p>Pilih dokumen untuk melihat bukti, baris dan tindakan berizin.</p>}</div></section>
    </div>
    {mode === "inventory" && data && <PeriodPanel data={data} allowed={allowed} onSaved={saved} />}
    {dialog && data && <DocumentForm data={data} kind={dialog.kind} source={dialog.source} onClose={() => setDialog(null)} onSaved={saved} />}
    {action && <DocumentAction doc={action.doc} action={action.action} onClose={() => setAction(null)} onSaved={saved} />}
  </div></AppShell>;
}

function DocumentForm({ data, kind, source, onClose, onSaved }: { data: Data; kind: Kind; source?: Doc; onClose: () => void; onSaved: () => void }) {
  const [lines, setLines] = useState<Line[]>([emptyLine()]), [busy, setBusy] = useState(false), [error, setError] = useState<ApiError | null>(null), [key] = useState(() => crypto.randomUUID());
  const update = (index: number, change: Partial<Line>) => setLines(rows => rows.map((row, i) => i === index ? { ...row, ...change } : row));
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(null);
    try {
      await requestJson("/api/inventory/documents", { requestKey: key, kind, effectiveAt: new Date(`${form.get("effectiveAt")}:00+07:00`).toISOString(), reason: form.get("reason"), evidence: form.get("evidence"), ...(["OPENING", "LEGACY_IMPORT"].includes(kind) ? { sourceName: form.get("sourceName"), checksum: form.get("checksum") } : kind === "RECEIPT" ? { sourceName: form.get("sourceName"), sourceType: form.get("sourceType") } : {}), ...(source ? { reversalOfId: source.id } : {}), lines: source ? [] : lines.map(row => ({ itemId: row.itemId, locationId: row.locationId, quantity: row.quantity, ...(kind === "TRANSFER" ? { destinationId: row.destinationId } : {}) })) });
      onSaved();
    } catch (caught) { setError(errorValue(caught)); } finally { setBusy(false); }
  }
  return <MasterDialog title={`${labels[kind]} baru`} busy={busy} onClose={onClose}><form onSubmit={submit}><div className="card-body master-form"><ErrorNotice error={error} />
    <p className="master-note">Quantity memakai UOM stok utama. Data master yang belum verified tidak dapat diposting. {kind === "INTERNAL_ISSUE" && "Konsumsi dari produksi tidak dicatat ulang sebagai CSR."}{kind === "OPNAME" && "Fisik diukur pada cut-off dengan bukti/metode; snapshot buku disimpan server."}{kind === "LEGACY_IMPORT" && "Masukkan saldo hasil rekonsiliasi seluruh event legacy sampai cut-off."}</p>
    {source && <p>Sumber reversal: {source.number}; baris diambil dari sumber, tanpa edit.</p>}
    <Field name="effectiveAt" label={kind === "OPNAME" ? "Cut-off fisik (WIB)" : "Tanggal efektif (WIB)"} errors={error}><input type="datetime-local" required defaultValue={localNow()} /></Field>
    <div id="field-lines" tabIndex={-1} className="master-form">{error?.errors.lines && <p className="form-error">{error.errors.lines.join(" ")}</p>}
    {!source && lines.map((line, index) => { const item = data.items.find(i => i.id === line.itemId); const locs = data.locations.filter(l => l.active && l.verificationStatus === "VERIFIED" && l.plant.active && l.plant.verificationStatus === "VERIFIED" && (!item || item.plants.some(p => p.plantId === l.plantId))); return <fieldset className="inventory-line" key={index}><legend>Baris {index + 1}</legend><div className="master-form">
      <Field name={`lines-${index}-itemId`} label="Material / UOM"><select required value={line.itemId} onChange={e => update(index, { itemId: e.target.value, locationId: "", destinationId: "" })}><option value="">Pilih material</option>{data.items.filter(i => i.active && i.verificationStatus === "VERIFIED" && i.kind !== "SERVICE" && i.primaryUom.active && i.primaryUom.verificationStatus === "VERIFIED" && i.primaryUom.dimension !== "UNKNOWN").map(i => <option key={i.id} value={i.id}>{i.name} / {i.primaryUom.code}</option>)}</select></Field>
      <Field name={`lines-${index}-locationId`} label="Lokasi sumber"><select required value={line.locationId} onChange={e => update(index, { locationId: e.target.value })}><option value="">Pilih lokasi</option>{locs.map(l => <option key={l.id} value={l.id}>{l.plant.name} / {l.name}</option>)}</select></Field>
      {kind === "TRANSFER" && <Field name={`lines-${index}-destinationId`} label="Lokasi tujuan"><select required value={line.destinationId ?? ""} onChange={e => update(index, { destinationId: e.target.value })}><option value="">Pilih tujuan berbeda</option>{locs.filter(l => l.id !== line.locationId).map(l => <option key={l.id} value={l.id}>{l.plant.name} / {l.name}</option>)}</select></Field>}
      <Field name={`lines-${index}-quantity`} label={kind === "OPNAME" ? `Fisik pada cut-off (${item?.primaryUom.code ?? "UOM"})` : kind === "ADJUSTMENT" ? "Selisih (+ masuk / − keluar)" : `Quantity (${item?.primaryUom.code ?? "UOM"})`}><input required inputMode="decimal" pattern="-?(0|[1-9][0-9]{0,17})([.][0-9]{1,6})?" value={line.quantity} onChange={e => update(index, { quantity: e.target.value })} /></Field>
      {lines.length > 1 && <button className="btn" type="button" onClick={() => setLines(rows => rows.filter((_, i) => i !== index))}>Hapus baris {index + 1}</button>}
    </div></fieldset>; })}
    </div>
    {!source && lines.length < 50 && <button className="btn" type="button" onClick={() => setLines(rows => [...rows, emptyLine()])}>Tambah baris material</button>}
    {kind === "RECEIPT" && <><Field name="sourceType" label="Jenis sumber receipt" errors={error}><select required defaultValue=""><option value="">Pilih jenis sumber</option><option value="SUPPLIER">Supplier</option><option value="QUARRY">Quarry</option><option value="INTERNAL">Internal</option></select></Field><Field name="sourceName" label="Sumber supplier / quarry / internal" errors={error}><input required minLength={3} maxLength={200} /></Field></>}
    {["OPENING", "LEGACY_IMPORT"].includes(kind) && <><Field name="sourceName" label="Nama sumber migration / workbook" errors={error}><input required minLength={3} maxLength={200} /></Field><Field name="checksum" label="SHA-256 sumber (64 karakter hex)" errors={error}><input required pattern="[a-fA-F0-9]{64}" maxLength={64} /></Field></>}
    <Field name="reason" label={kind === "INTERNAL_ISSUE" ? "Tujuan / penerima CSR dan alasan" : "Alasan"} errors={error}><textarea required minLength={5} maxLength={1000} rows={2} /></Field>
    <Field name="evidence" label="Bukti / referensi dokumen / metode ukur" errors={error}><textarea required minLength={5} maxLength={1000} rows={2} /></Field>
  </div><div className="master-actions"><button className="btn" type="button" onClick={onClose} disabled={busy}>Batal</button><button className="btn primary" disabled={busy}>{busy ? "Menyimpan..." : "Simpan & ajukan"}</button></div></form></MasterDialog>;
}

function DocumentAction({ doc, action, onClose, onSaved }: { doc: Doc; action: string; onClose: () => void; onSaved: () => void }) {
  const [busy, setBusy] = useState(false), [error, setError] = useState<ApiError | null>(null);
  return <MasterDialog title={`${action === "approve" ? "Approve & post" : action === "finance" ? "Verifikasi Finance" : action === "reject" ? "Tolak" : "Post"} ${doc.number}`} onClose={onClose} busy={busy}><form onSubmit={async e => { e.preventDefault(); setBusy(true); setError(null); try { await requestJson(`/api/inventory/documents/${doc.id}`, { action, reason: new FormData(e.currentTarget).get("reason") }); onSaved(); } catch (caught) { setError(errorValue(caught)); } finally { setBusy(false); } }}><div className="card-body master-form"><ErrorNotice error={error} /><p>{doc.lines.length} baris · {time(doc.effectiveAt)} WIB. Server memeriksa ulang stok, periode, scope dan dependency sebelum posting.</p><Field name="reason" label="Alasan keputusan / referensi rekonsiliasi" errors={error}><textarea required minLength={5} maxLength={1000} rows={3} /></Field></div><div className="master-actions"><button type="button" className="btn" disabled={busy} onClick={onClose}>Batal</button><button className="btn primary" disabled={busy}>{busy ? "Memproses..." : "Konfirmasi tindakan"}</button></div></form></MasterDialog>;
}

function PeriodPanel({ data, allowed, onSaved }: { data: Data; allowed: (permission: string) => boolean; onSaved: () => void }) {
  const [plantId, setPlantId] = useState(""), [month, setMonth] = useState(localNow().slice(0, 7)), [action, setAction] = useState("request-close"), [error, setError] = useState<ApiError | null>(null), [busy, setBusy] = useState(false);
  const plants = [...new Map(data.locations.map(l => [l.plantId, l.plant])).entries()], period = data.periods.find(p => p.plantId === plantId && p.month === month);
  const actions = [["request-close", "inventory.period.request", "Ajukan close"], ["request-reopen", "inventory.period.request", "Ajukan reopen"], ["finance", "inventory.period.reconcile", "Rekonsiliasi Finance"], ["approve", "inventory.period.approve", "Approve periode"], ["reject", "inventory.period.approve", "Tolak permintaan"]].filter(([, permission]) => allowed(permission));
  const selectedAction = actions.some(([value]) => value === action) ? action : actions[0]?.[0];
  return <section className="card"><div className="card-body master-form"><h2>Kontrol periode inventory</h2><p className="master-note">Lock berlaku pada ledger inventory baru. Closing lintas keuangan/produksi dan checklist lengkap tetap memerlukan fondasi S2.</p><ErrorNotice error={error} /><form className="master-form" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(null); try { await requestJson("/api/inventory/periods", { plantId, month, action: selectedAction, version: period?.version ?? 0, reason: new FormData(e.currentTarget).get("periodReason") }); onSaved(); } catch (caught) { setError(errorValue(caught)); } finally { setBusy(false); } }}>
    <div className="form-grid"><Field name="periodPlant" label="Plant"><select required value={plantId} onChange={e => setPlantId(e.target.value)}><option value="">Pilih plant</option>{plants.map(([id, p]) => <option key={id} value={id}>{p.name}</option>)}</select></Field><Field name="month" label="Periode (WIB)"><input type="month" required value={month} onChange={e => setMonth(e.target.value)} /></Field></div>
    <p>Status: {period?.closed ? "Tertutup" : "Terbuka"}{period?.requestedBy && ` · Permintaan ${period.requestClose ? "close" : "reopen"} menunggu keputusan`}</p>
    {actions.length > 0 && <><Field name="periodAction" label="Tindakan periode"><select value={actions.some(([value]) => value === action) ? action : actions[0][0]} onChange={e => setAction(e.target.value)}>{actions.map(([value, , label]) => <option key={value} value={value}>{label}</option>)}</select></Field><Field name="periodReason" label="Alasan / bukti rekonsiliasi"><textarea required minLength={5} maxLength={1000} rows={2} /></Field><button className="btn" disabled={busy}>{busy ? "Memproses..." : "Simpan tindakan periode"}</button></>}
  </form></div></section>;
}
