"use client";
import { useEffect, useState, FormEvent } from "react";
import { AppShell } from "./app-shell";
import { ApiError, ErrorNotice, Field, MasterDialog, errorValue, requestJson } from "./master-fields";
import { useSession } from "./session-provider";
import { can } from "@/lib/access";
import type { RunInput, ConfigInput } from "@/features/operations/schema";
import type { RunSnapshot } from "@/features/operations/service";
import { LocalDraft as AnyLocalDraft, localDrafts, saveLocalDraft, syncLocalDraft, forkLocalDraft, removeLocalDraft, rememberReferences, offlineReferences, prepareOfflineShell } from "@/lib/offline-drafts";

type LocalDraft = AnyLocalDraft<RunInput>;
type Config = { id: string; plantId: string; code: string; revision: number; kind: string; makerId: string; verificationStatus: string; effectiveFrom: string; evidence: string; verificationEvidence: string | null; payload: ConfigInput["payload"] };
type Run = { id: string; number: string; kind: string; plantId: string; status: string; version: number; makerId: string; submitterId: string | null; payload: RunInput; snapshot: RunSnapshot | null; stockDocumentId: string | null; decisionEvidence: string | null };
type Data = { month: string; runs: Run[]; total: number; plants: { id: string; name: string; kind: string; verificationStatus: string; active: boolean }[]; configs: Config[]; locations: { id: string; name: string; kind: string; plantId: string; active: boolean; verificationStatus: string }[]; items: { id: string; name: string; kind: string; active: boolean; verificationStatus: string; primaryUomId: string; primaryUom: { code: string }; plants: { plantId: string }[] }[]; uoms: { id: string; code: string }[]; conversions: { id: string; itemId: string; fromUomId: string; toUomId: string; factor: string; version: number }[]; usages: { id: string; number: string; plantId: string; effectiveAt: string; payload: RunInput }[]; tankBalances: { locationId: string; itemId: string; liters: string }[]; assetUsage: { name: string; assetId: string; plantId: string; liters: string }[]; kpis: { plantId: string; plantName: string; liters: string; output: string; ratio: string | null; unit: string; exception: string | null }[] };
const labels: Record<string, string> = { SC: "SC · input harian", BP: "BP · batch & mutu", AMP: "AMP · tonase & rekonsiliasi", BLENDING: "Blending · komponen → hasil", FUEL_RECEIPT: "Receipt BBM", FUEL_USAGE: "Pemakaian BBM", FUEL_TRANSFER: "Transfer tangki" };
const statuses: Record<string, string> = { DRAFT: "Draft", SUBMITTED: "Menunggu verifikasi", VERIFIED: "Terverifikasi", POSTED: "Posted", REJECTED: "Ditolak", REVERSED: "Dibalik" };
const localNow = () => new Date(Date.now() + 7 * 3600000).toISOString().slice(0, 16);
const localDate = (value: string) => new Date(new Date(value).getTime() + 7 * 3600000).toISOString().slice(0, 16);
const newLine = () => ({ itemId: "", locationId: "", uomId: "", quantity: "" });
const valid = (row: { active: boolean; verificationStatus: string }) => row.active && row.verificationStatus === "VERIFIED";
function draftReferences(data: Data, domain: string): Data {
  return { month: data.month, runs: [], total: 0, usages: [], tankBalances: [], assetUsage: [], kpis: [],
    plants: data.plants.filter(valid).map(({ id, name, kind, active, verificationStatus }) => ({ id, name, kind, active, verificationStatus })),
    locations: data.locations.filter(valid).map(({ id, name, kind, plantId, active, verificationStatus }) => ({ id, name, kind, plantId, active, verificationStatus })),
    items: data.items.filter(valid).map(({ id, name, kind, active, verificationStatus, primaryUomId, primaryUom, plants }) => ({ id, name, kind, active, verificationStatus, primaryUomId, primaryUom: { code: primaryUom.code }, plants: plants.map(({ plantId }) => ({ plantId })) })),
    uoms: data.uoms.map(({ id, code }) => ({ id, code })), conversions: data.conversions.map(({ id, itemId, fromUomId, toUomId, factor, version }) => ({ id, itemId, fromUomId, toUomId, factor, version })),
    configs: data.configs.filter(c => c.verificationStatus === "VERIFIED" && (domain === "fuel" ? ["FUEL", "ASSET"] : ["PRODUCT", "MIX"]).includes(c.kind)).map(c => ({ id: c.id, plantId: c.plantId, code: c.code, revision: c.revision, kind: c.kind, verificationStatus: c.verificationStatus, effectiveFrom: c.effectiveFrom, makerId: "", evidence: "", verificationEvidence: null, payload: c.payload.kind === "ASSET" ? { ...c.payload, contract: "", ownership: "", payer: "", costResponsibility: "" } : c.payload })),
  };
}

export function PlantOperations({ domain }: { domain: "production" | "blending" | "fuel" }) {
  const { session } = useSession(), prefix = domain === "fuel" ? "fuel" : "production";
  const [data, setData] = useState<Data | null>(null), [error, setError] = useState<ApiError | null>(null), [loading, setLoading] = useState(true);
  const [month, setMonth] = useState(localNow().slice(0, 7)), [plantId, setPlantId] = useState(""), [page, setPage] = useState(1), [selected, setSelected] = useState<Run | null>(null);
  const [form, setForm] = useState<{ kind: RunInput["kind"]; run?: Run; local?: LocalDraft } | null>(null), [configKind, setConfigKind] = useState<ConfigInput["payload"]["kind"] | null>(null);
  const [drafts, setDrafts] = useState<LocalDraft[]>([]), [syncing, setSyncing] = useState(false), [offline, setOffline] = useState(false);
  const [decision, setDecision] = useState<{ run?: Run; config?: Config; action: string } | null>(null);
  const allowed = (p: string) => !!session && can(session, p);
  async function load() {
    setLoading(true); setError(null);
    try { const next = await requestJson<Data>(`/api/operations?${new URLSearchParams({ domain, month, plantId, page: String(page) })}`); setData(next); setOffline(false); setSelected(old => next.runs.find(r => r.id === old?.id) ?? null); if (session && domain !== "blending" && can(session, `${prefix}.create`)) { await rememberReferences(session, domain, draftReferences(next, domain)); await prepareOfflineShell(); } }
    catch (caught) { const cached = session && !navigator.onLine && domain !== "blending" ? await offlineReferences<Data>(session.userId, domain).catch(() => undefined) : undefined; if (cached) { setData(cached); setSelected(null); setOffline(true); } else { setData(null); setSelected(null); setError(errorValue(caught)); } } finally { setLoading(false); }
  }
  useEffect(() => { if (session) void load(); else { setData(null); setSelected(null); setDrafts([]); setForm(null); } }, [domain, month, plantId, page, session]);
  useEffect(() => { const refresh = () => { if (session) void localDrafts(session.userId).then(rows => setDrafts(rows.filter((d): d is LocalDraft => d.payload.kind !== "INSPECTION"))).catch(() => setDrafts([])); }; refresh(); window.addEventListener("quarryflow-drafts", refresh); return () => window.removeEventListener("quarryflow-drafts", refresh); }, [session]);
  const saved = () => { setForm(null); setConfigKind(null); setDecision(null); void load(); };
  const title = domain === "production" ? "Produksi SC / BP / AMP" : domain === "blending" ? "Blending" : "BBM";
  const kinds: RunInput["kind"][] = domain === "production" ? ["SC", "BP", "AMP"] : domain === "blending" ? ["BLENDING"] : ["FUEL_RECEIPT", "FUEL_USAGE", "FUEL_TRANSFER"];
  return <AppShell active={domain === "production" ? "Production" : domain === "blending" ? "Blending" : "BBM"}><div className="content master-page">
    <div className="page-head"><div><span className="eyebrow">Operasional / {domain === "fuel" ? "BBM" : "produksi"}</span><h1>{title}</h1><p>{domain === "fuel" ? "Liter aktual, satu ledger, saldo tangki dan monitoring alat." : domain === "blending" ? "Komponen bahan dikonsumsi untuk hasil blending terukur." : "SC harian, BP per batch/mutu, AMP tonase. Posting memakai konsumsi aktual."}</p></div><div className="master-inline-actions">{allowed(`${prefix}.create`) && kinds.map(kind => <button key={kind} disabled={loading || !data} className="btn primary" onClick={() => setForm({ kind })}>{labels[kind]} baru</button>)}</div></div>
    <div className="master-toolbar"><Field name="operationPlant" label="Plant"><select value={plantId} onChange={e => { setPlantId(e.target.value); setPage(1); }}><option value="">Semua plant dalam cakupan</option>{data?.plants.map(p => <option key={p.id} value={p.id}>{p.name} · {p.kind}</option>)}</select></Field><Field name="operationMonth" label="Periode WIB"><input type="month" required value={month} onChange={e => { setMonth(e.target.value); setPage(1); }} /></Field><button className="btn" disabled={loading} onClick={() => void load()}>Muat ulang</button></div>
    <ErrorNotice error={error} />{loading && <p role="status">Memuat transaksi...</p>}
    {domain !== "blending" && session && <section className="card"><div className="card-body"><h2>Draft perangkat</h2><p>{offline ? "Offline: referensi terakhir tersimpan, saldo dan transaksi server tidak tersedia." : "Draft perangkat belum menjadi transaksi resmi sebelum sync."} Verifikasi, posting dan pembayaran memerlukan koneksi. {drafts.filter(d => domain === "fuel" ? d.payload.kind.startsWith("FUEL_") : !d.payload.kind.startsWith("FUEL_")).length} draft tersimpan.</p>{drafts.filter(d => domain === "fuel" ? d.payload.kind.startsWith("FUEL_") : !d.payload.kind.startsWith("FUEL_")).map(d => <article key={d.id} className="master-detail"><strong>{labels[d.payload.kind]} · {d.payload.pic || "Belum diisi"}</strong><p>{d.state} · UUID {d.id}<br />{d.error}</p><div className="master-inline-actions"><button className="btn" disabled={syncing || !data} onClick={() => setForm({ kind: d.payload.kind, local: d })}>Edit perangkat</button><button className="btn primary" disabled={offline || syncing} onClick={async () => { setSyncing(true); setError(null); try { await syncLocalDraft(d); await load(); } catch (caught) { setError(new ApiError(caught instanceof Error ? caught.message : "Sync gagal.")); } finally { setSyncing(false); } }}>Sync draft</button>{d.state === "CONFLICT" && <><button className="btn" disabled={offline || syncing} onClick={async () => { try { const source = data?.runs.find(r => r.id === d.sourceId || r.payload.requestKey === d.id); if (!source) throw new Error("Pilih periode/plant sumber dan muat ulang untuk membandingkan konflik."); setSelected(source); } catch (caught) { setError(new ApiError((caught as Error).message)); } }}>Bandingkan server</button><button className="btn" disabled={syncing} onClick={async () => { try { await forkLocalDraft(d); } catch (caught) { setError(new ApiError((caught as Error).message)); } }}>Salin ke UUID baru</button></>}<button className="btn" disabled={syncing} onClick={async () => { try { await removeLocalDraft(d); } catch (caught) { setError(new ApiError((caught as Error).message)); } }}>Hapus perangkat</button></div></article>)}</div></section>}
    {data && domain === "fuel" && <>
      <section className="card"><div className="card-body"><h2>Saldo per tangki (liter)</h2><div className="data-scroll"><table className="data-table"><thead><tr><th>Tangki / plant</th><th>BBM</th><th>Liter</th></tr></thead><tbody>{data.tankBalances.map(b => <tr key={`${b.locationId}:${b.itemId}`}><td>{data.locations.find(l => l.id === b.locationId)?.name}<br />{data.plants.find(p => p.id === data.locations.find(l => l.id === b.locationId)?.plantId)?.name}</td><td>{data.items.find(i => i.id === b.itemId)?.name}</td><td>{b.liters}</td></tr>)}{!data.tankBalances.length && <tr><td colSpan={3}>Belum ada saldo tangki posted.</td></tr>}</tbody></table></div></div></section>
      <section className="card"><div className="card-body"><h2>BBM produksi / output · {data.month}</h2><div className="data-scroll"><table className="data-table"><thead><tr><th>Plant</th><th>Liter eligible</th><th>Output terukur</th><th>Rasio</th><th>Exception</th></tr></thead><tbody>{data.kpis.map(k => <tr key={k.plantId}><td>{k.plantName}</td><td>{k.liters}</td><td>{k.output} {k.unit === "liter/ton" ? "ton" : "m³"}</td><td>{k.ratio ?? "N/A"} {k.unit}</td><td>{k.exception ?? "—"}</td></tr>)}</tbody></table></div><h3>Pemakaian per alat · semua purpose</h3>{data.assetUsage.map(a => <p key={a.assetId}>{a.name}: {a.liters} liter</p>)}{!data.assetUsage.length && <p>Belum ada usage posted pada periode ini.</p>}</div></section>
    </>}
    {data && <><div className="master-workspace"><section className="card table-card"><div className="card-head"><h2>Worklist transaksi</h2></div><div className="data-scroll"><table className="data-table master-list-table"><thead><tr><th>Sumber</th><th>Plant / proses</th><th>Status</th><th>Detail</th></tr></thead><tbody>{data.runs.map(run => <tr key={run.id}><td>{run.number}<br />{localDate(run.payload.effectiveAt).replace("T", " ")}</td><td>{data.plants.find(p => p.id === run.plantId)?.name}<br />{labels[run.kind]}</td><td>{statuses[run.status]}</td><td><button className="btn" disabled={loading} onClick={() => setSelected(run)}>Buka</button></td></tr>)}{!data.runs.length && <tr><td colSpan={4}>Belum ada transaksi pada plant/periode ini.</td></tr>}</tbody></table></div><div className="master-actions"><button className="btn" disabled={page === 1 || loading} onClick={() => setPage(n => n - 1)}>Sebelumnya</button><span>Halaman {page}</span><button className="btn" disabled={page * 30 >= data.total || loading} onClick={() => setPage(n => n + 1)}>Berikutnya</button></div></section>
    <section className="card"><div className="card-body master-detail">{selected ? <><h2>{selected.number}</h2><p>{statuses[selected.status]} · PIC {selected.payload.pic}</p><p>Metode: {selected.payload.method}<br />Bukti: {selected.payload.evidence}</p>{selected.payload.batch && <p>Batch: {selected.payload.batch}<br />Mutu / rekonsiliasi: {selected.payload.quality}</p>}
      {selected.payload.fuel ? <p>{selected.payload.fuel.liters} liter · {selected.payload.fuel.purpose ?? selected.kind}<br />Alat: {data.configs.find(c => c.id === selected.payload.fuel?.assetId)?.code ?? "—"}<br />Sumber: {selected.payload.fuel.sourceName ?? "—"}</p> : <div className="data-scroll"><table className="data-table"><thead><tr><th>Peran</th><th>Material / lokasi</th><th>Aktual</th><th>Stok verified</th></tr></thead><tbody>{[...selected.payload.inputs.map(l => ({ ...l, role: "INPUT" })), ...selected.payload.outputs.map(l => ({ ...l, role: "OUTPUT" }))].map((l, i) => <tr key={i}><td>{l.role === "INPUT" ? "Bahan" : "Hasil"}</td><td>{data.items.find(x => x.id === l.itemId)?.name}<br />{data.locations.find(x => x.id === l.locationId)?.name}</td><td>{l.quantity} {data.uoms.find(x => x.id === l.uomId)?.code}</td><td>{selected.snapshot?.lines.find(x => x.role === l.role && x.itemId === l.itemId && x.locationId === l.locationId)?.stockQuantity ?? "Belum verified"}</td></tr>)}</tbody></table></div>}
      {selected.kind === "AMP" && selected.snapshot && <p>Rekonsiliasi terukur: input {selected.snapshot.reconciliation.inputTon ?? "N/A — density belum tersedia"} ton · output {selected.snapshot.reconciliation.outputTon} ton · selisih {selected.snapshot.reconciliation.varianceTon ?? "N/A"} ton.</p>}
      {selected.payload.fuelUsageId && <p>BBM AMP: usage {selected.payload.fuelUsageId}; stok sudah dipotong pada usage.</p>}
      {!!selected.snapshot?.comparison.length && <div className="data-scroll"><table className="data-table"><caption>Mix version vs konsumsi aktual (UOM stok)</caption><thead><tr><th>Bahan</th><th>Design</th><th>Aktual</th><th>Selisih</th></tr></thead><tbody>{selected.snapshot.comparison.map(c => <tr key={c.itemId}><td>{c.itemName} / {c.uom}</td><td>{c.expected}</td><td>{c.actual}</td><td>{c.variance}</td></tr>)}</tbody></table></div>}
      {selected.stockDocumentId && <p><a href="/inventory">Ledger sumber {selected.stockDocumentId}</a></p>}<p>{selected.decisionEvidence}</p><div className="master-inline-actions">
        {selected.status === "DRAFT" && selected.makerId === session?.userId && allowed(`${prefix}.create`) && <><button className="btn" onClick={() => setForm({ kind: selected.kind as RunInput["kind"], run: selected })}>Edit draft</button><button className="btn primary" onClick={() => setDecision({ run: selected, action: "submit" })}>Submit</button></>}
        {["DRAFT", "VERIFIED"].includes(selected.status) && selected.makerId !== session?.userId && allowed(`${prefix}.verify`) && <button className="btn" onClick={() => setDecision({ run: selected, action: "reject" })}>Tolak sumber</button>}
        {selected.status === "SUBMITTED" && selected.makerId !== session?.userId && selected.submitterId !== session?.userId && allowed(`${prefix}.verify`) && <><button className="btn primary" onClick={() => setDecision({ run: selected, action: "verify" })}>Verifikasi PC</button><button className="btn" onClick={() => setDecision({ run: selected, action: "reject" })}>Tolak</button></>}
        {selected.status === "VERIFIED" && allowed(`${prefix}.post`) && <button className="btn primary" onClick={() => setDecision({ run: selected, action: "post" })}>Post ke ledger</button>}
      </div></> : <p>Pilih sumber untuk melihat input-output, bukti, verifikasi dan ledger.</p>}</div></section></div>
      <section className="card"><div className="card-body"><h2>{domain === "fuel" ? "Aturan BBM & register alat minimum" : "Klasifikasi hasil & mix design version"}</h2><p>Version baru harus disahkan Manager berbeda maker. Data perusahaan dan faktor konversi tidak diisi otomatis.</p><div className="master-inline-actions">{allowed(`${prefix}.config.create`) && (domain === "fuel" ? ["FUEL", "ASSET"] as const : ["PRODUCT", "MIX"] as const).map(kind => <button key={kind} className="btn" onClick={() => setConfigKind(kind)}>{kind === "FUEL" ? "Definisi BBM" : kind === "ASSET" ? "Alat & aturan KPI" : kind === "PRODUCT" ? "Klasifikasi hasil" : "Mix version baru"}</button>)}</div><div className="data-scroll"><table className="data-table"><thead><tr><th>Konfigurasi</th><th>Versi / berlaku</th><th>Status / bukti</th><th>Tindakan</th></tr></thead><tbody>{data.configs.filter(c => domain === "fuel" ? ["FUEL", "ASSET"].includes(c.kind) : ["PRODUCT", "MIX"].includes(c.kind)).map(c => <tr key={c.id}><td>{c.code} · {c.kind}{c.payload.kind === "ASSET" && <><br />{c.payload.name} · {c.payload.identity}<br />{c.payload.ownership} / {c.payload.payer} / {c.payload.costResponsibility}<br />KPI produksi: {c.payload.eligibleProduction ? "Eligible" : "Dikecualikan dengan bukti"}</>}{c.payload.kind === "PRODUCT" && <><br />{data.items.find(i => c.payload.kind === "PRODUCT" && i.id === c.payload.itemId)?.name} / {c.payload.process}</>}{c.payload.kind === "MIX" && <><br />{c.payload.process} · {c.payload.components.map(x => `${data.items.find(i => i.id === x.itemId)?.name}: ${x.quantity} ${data.uoms.find(u => u.id === x.uomId)?.code}`).join("; ")} per 1 output</>}</td><td>{c.revision}<br />{localDate(c.effectiveFrom).slice(0, 10)}</td><td>{c.verificationStatus}<br />{c.evidence}<br />{c.verificationEvidence}</td><td>{c.verificationStatus === "UNVERIFIED" && c.makerId !== session?.userId && allowed(`${prefix}.config.verify`) && <button className="btn" onClick={() => setDecision({ config: c, action: "config" })}>Verifikasi konfigurasi</button>}</td></tr>)}</tbody></table></div></div></section>
    </>}
    {form && data && <RunForm data={data} kind={form.kind} run={form.run} local={form.local} ownerId={session!.userId} initialPlant={plantId} onClose={() => setForm(null)} onSaved={saved} />}
    {configKind && data && <ConfigForm data={data} kind={configKind} initialPlant={plantId} onClose={() => setConfigKind(null)} onSaved={saved} />}
    {decision && <Decision value={decision} onClose={() => setDecision(null)} onSaved={saved} />}
  </div></AppShell>;
}

function PlantField({ data, value, onChange, disabled = false }: { data: Data; value: string; onChange: (value: string) => void; disabled?: boolean }) {
  return <Field name="plantId" label="Plant transaksi"><select required disabled={disabled} value={value} onChange={e => onChange(e.target.value)}><option value="">Pilih plant</option>{data.plants.filter(valid).map(p => <option key={p.id} value={p.id}>{p.name} / {p.kind}</option>)}</select></Field>;
}
function MaterialRows({ data, plantId, rows, onChange, title, output = false, locations = true }: { data: Data; plantId: string; rows: RunInput["inputs"]; onChange: (rows: RunInput["inputs"]) => void; title: string; output?: boolean; locations?: boolean }) {
  const update = (index: number, changes: Partial<RunInput["inputs"][number]>) => onChange(rows.map((r, i) => i === index ? { ...r, ...changes } : r));
  return <fieldset className="inventory-lines"><legend>{title}</legend>{rows.map((row, i) => <fieldset className="inventory-line" key={i}><legend>Baris {i + 1}</legend>
    <Field name={`${output ? "output" : "input"}-${i}-itemId`} label="Material"><select required value={row.itemId} onChange={e => { const material = data.items.find(x => x.id === e.target.value); update(i, { itemId: e.target.value, uomId: output ? "" : material?.primaryUomId ?? "", conversionId: undefined }); }}><option value="">Pilih material</option>{data.items.filter(x => valid(x) && x.kind !== "SERVICE" && (!output || x.kind === "PRODUCT") && x.plants.some(p => p.plantId === plantId)).map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></Field>
    {locations && <Field name={`${output ? "output" : "input"}-${i}-locationId`} label={output ? "Lokasi hasil" : "Lokasi bahan"}><select required value={row.locationId} onChange={e => update(i, { locationId: e.target.value })}><option value="">Pilih lokasi</option>{data.locations.filter(x => valid(x) && x.plantId === plantId && x.kind !== "TANK").map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></Field>}
    <Field name={`${output ? "output" : "input"}-${i}-uomId`} label="UOM aktual"><select required value={row.uomId} onChange={e => update(i, { uomId: e.target.value, conversionId: undefined })}><option value="">Pilih UOM</option>{data.uoms.map(x => <option key={x.id} value={x.id}>{x.code}</option>)}</select></Field>
    <Field name={`${output ? "output" : "input"}-${i}-quantity`} label={locations ? "Quantity terukur" : "Quantity per 1 output"}><input required inputMode="decimal" pattern="[0-9]+([.][0-9]{1,6})?" value={row.quantity} onChange={e => update(i, { quantity: e.target.value })} /></Field>
    <Field name={`${output ? "output" : "input"}-${i}-conversionId`} label="Konversi / density version"><select value={row.conversionId ?? ""} onChange={e => update(i, { conversionId: e.target.value || undefined })}><option value="">UOM sama / konversi standar</option>{data.conversions.filter(x => x.itemId === row.itemId && x.fromUomId === row.uomId).map(x => <option key={x.id} value={x.id}>v{x.version} × {x.factor}</option>)}</select></Field>
    {rows.length > 1 && <button className="btn" type="button" onClick={() => onChange(rows.filter((_, n) => n !== i))}>Hapus baris</button>}
  </fieldset>)}<button type="button" className="btn" onClick={() => onChange([...rows, newLine()])}>Tambah baris {output ? "hasil" : "bahan"}</button></fieldset>;
}
function RunForm({ data, kind, run, local, ownerId, initialPlant, onClose, onSaved }: { data: Data; kind: RunInput["kind"]; run?: Run; local?: LocalDraft; ownerId: string; initialPlant: string; onClose: () => void; onSaved: () => void }) {
  const [payload, setPayload] = useState<RunInput>(local?.payload ?? run?.payload ?? { requestKey: crypto.randomUUID(), kind, plantId: initialPlant, effectiveAt: `${localNow()}:00+07:00`, pic: "", method: "", evidence: "", reason: "", batch: "", quality: "", inputs: kind.startsWith("FUEL_") ? [] : [newLine()], outputs: kind.startsWith("FUEL_") ? [] : [newLine()], ...(kind.startsWith("FUEL_") ? { fuel: { policyId: "", tankId: "", liters: "" } } : {}) });
  const [busy, setBusy] = useState(false), [error, setError] = useState<ApiError | null>(null);
  const change = (value: Partial<RunInput>) => setPayload(old => ({ ...old, ...value }));
  const fuel = (value: Partial<NonNullable<RunInput["fuel"]>>) => change({ fuel: { ...payload.fuel!, ...value } });
  const configs = data.configs.filter(c => c.plantId === payload.plantId && c.verificationStatus === "VERIFIED");
  const saveDevice = async () => { setBusy(true); setError(null); try { await saveLocalDraft(ownerId, payload, run, local?.revision); onSaved(); } catch (caught) { setError(new ApiError(caught instanceof Error ? caught.message : "Draft perangkat gagal disimpan.")); } finally { setBusy(false); } };
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (local || !navigator.onLine) { await saveDevice(); return; } setBusy(true); setError(null); try { await requestJson(run ? `/api/operations/runs/${run.id}` : "/api/operations", { payload, version: run?.version ?? 0 }, run ? "PATCH" : "POST"); onSaved(); } catch (caught) { setError(errorValue(caught)); } finally { setBusy(false); } };
  return <MasterDialog title={`${labels[kind]} · ${run ? "edit" : "baru"}`} onClose={onClose} busy={busy}><form onSubmit={submit}><div className="card-body master-form" id="field-payload" tabIndex={-1}><ErrorNotice error={error} />
    <PlantField data={data} value={payload.plantId} disabled={!!run || !!local?.sourceId} onChange={plantId => { if (!run && !local?.sourceId) change({ plantId, inputs: payload.inputs.map(() => newLine()), outputs: payload.outputs.map(() => newLine()), mixVersionId: undefined, fuelUsageId: undefined, fuel: payload.fuel ? { policyId: "", tankId: "", liters: payload.fuel.liters } : undefined }); }} />
    <Field name="effectiveAt" label="Tanggal ukur WIB"><input required type="datetime-local" value={localDate(payload.effectiveAt)} onChange={e => change({ effectiveAt: `${e.target.value}:00+07:00` })} /></Field>
    <Field name="pic" label="PIC lapangan"><input required value={payload.pic} onChange={e => change({ pic: e.target.value })} /></Field>
    {kind === "SC" && <p>Input harian: bahan aktual → hasil ukur m³. Produk blending memakai transaksi blending tersendiri.</p>}
    {kind === "BP" && <p>Workspace batch/mutu: hasil beton m³, konsumsi bahan aktual dan pembanding mix version.</p>}
    {kind === "AMP" && <p>Rekonsiliasi tonase: hasil hotmix ton, bahan aktual dan bukti timbang. Tautkan usage BBM yang sudah posted.</p>}
    {kind === "BLENDING" && <p>Komponen bahan → hasil blending; konsumsi dan hasil diposting bersama.</p>}
    {["BP", "AMP"].includes(kind) && <><Field name="batch" label="Nomor batch"><input required value={payload.batch} onChange={e => change({ batch: e.target.value })} /></Field><Field name="quality" label={kind === "BP" ? "Mutu / referensi uji" : "Rekonsiliasi tonase / referensi timbang"}><textarea required value={payload.quality} onChange={e => change({ quality: e.target.value })} /></Field></>}
    {!payload.fuel && <><MaterialRows data={data} plantId={payload.plantId} rows={payload.inputs} onChange={inputs => change({ inputs })} title={kind === "BLENDING" ? "Komponen bahan aktual" : "Konsumsi bahan aktual"} /><div aria-hidden="true">↓</div><MaterialRows data={data} plantId={payload.plantId} rows={payload.outputs} onChange={outputs => change({ outputs })} title={kind === "SC" ? "Hasil ukur harian (M3)" : kind === "BP" ? "Hasil batch beton (M3)" : kind === "AMP" ? "Hasil hotmix (TON)" : "Hasil blending terukur"} output />
      <Field name="mixVersionId" label="Mix design version"><select required={kind !== "SC"} value={payload.mixVersionId ?? ""} onChange={e => change({ mixVersionId: e.target.value || undefined })}><option value="">{kind === "SC" ? "Tanpa pembanding" : "Pilih version verified"}</option>{configs.filter(c => c.payload.kind === "MIX" && c.payload.process === kind).map(c => <option key={c.id} value={c.id}>{c.code} v{c.revision}</option>)}</select></Field>
      {kind === "AMP" && <Field name="fuelUsageId" label="BBM proses · usage posted"><select value={payload.fuelUsageId ?? ""} onChange={e => change({ fuelUsageId: e.target.value || undefined })}><option value="">Tidak ada BBM proses pada batch ini</option>{data.usages.filter(u => u.plantId === payload.plantId && u.payload.fuel?.purpose === "PRODUCTION").map(u => <option key={u.id} value={u.id}>{u.number} / {u.payload.fuel?.liters} liter</option>)}</select></Field>}
    </>}
    {payload.fuel && <><Field name="fuelPolicy" label="Definisi BBM verified"><select required value={payload.fuel.policyId} onChange={e => fuel({ policyId: e.target.value })}><option value="">Pilih BBM</option>{configs.filter(c => c.kind === "FUEL").map(c => <option key={c.id} value={c.id}>{c.code} v{c.revision}</option>)}</select></Field>
      <Field name="tankId" label="Tangki sumber / penerimaan"><select required value={payload.fuel.tankId} onChange={e => fuel({ tankId: e.target.value })}><option value="">Pilih tangki</option>{data.locations.filter(l => valid(l) && l.plantId === payload.plantId && l.kind === "TANK").map(l => <option key={l.id} value={l.id}>{l.name}</option>)}</select></Field>
      <Field name="liters" label="Liter aktual"><input required inputMode="decimal" pattern="[0-9]+([.][0-9]{1,6})?" value={payload.fuel.liters} onChange={e => fuel({ liters: e.target.value })} /></Field>
      {kind === "FUEL_TRANSFER" && <Field name="destinationId" label="Tangki tujuan"><select required value={payload.fuel.destinationId ?? ""} onChange={e => fuel({ destinationId: e.target.value })}><option value="">Pilih tangki berbeda</option>{data.locations.filter(l => valid(l) && l.kind === "TANK" && l.id !== payload.fuel?.tankId).map(l => <option key={l.id} value={l.id}>{data.plants.find(p => p.id === l.plantId)?.name} / {l.name}</option>)}</select></Field>}
      {kind === "FUEL_USAGE" && <><Field name="assetId" label="Alat / kendaraan verified"><select required value={payload.fuel.assetId ?? ""} onChange={e => fuel({ assetId: e.target.value })}><option value="">Pilih alat</option>{configs.filter(c => c.payload.kind === "ASSET").map(c => <option key={c.id} value={c.id}>{c.payload.kind === "ASSET" ? c.payload.name : c.code} v{c.revision}</option>)}</select></Field><Field name="purpose" label="Purpose pemakaian"><select required value={payload.fuel.purpose ?? ""} onChange={e => fuel({ purpose: e.target.value as "PRODUCTION" | "NON_PRODUCTION" })}><option value="">Pilih purpose</option><option value="PRODUCTION">Produksi plant</option><option value="NON_PRODUCTION">Nonproduksi</option></select></Field></>}
      {kind === "FUEL_RECEIPT" && <><Field name="sourceType" label="Jenis sumber BBM"><select required value={payload.fuel.sourceType ?? ""} onChange={e => fuel({ sourceType: e.target.value as "SUPPLIER" | "QUARRY" | "INTERNAL" })}><option value="">Pilih sumber</option><option value="SUPPLIER">Supplier</option><option value="QUARRY">Quarry</option><option value="INTERNAL">Internal</option></select></Field><Field name="sourceName" label="Nama / dokumen sumber"><input required value={payload.fuel.sourceName ?? ""} onChange={e => fuel({ sourceName: e.target.value })} /></Field></>}
    </>}
    <Field name="method" label="Metode ukur / alat ukur"><textarea required minLength={5} value={payload.method} onChange={e => change({ method: e.target.value })} /></Field><Field name="evidence" label="Bukti / dokumen sumber"><textarea required minLength={5} value={payload.evidence} onChange={e => change({ evidence: e.target.value })} /></Field><Field name="reason" label="Tujuan / alasan"><textarea required minLength={5} value={payload.reason} onChange={e => change({ reason: e.target.value })} /></Field>
  </div><div className="master-actions"><button type="button" className="btn" disabled={busy} onClick={onClose}>Batal</button>{kind !== "BLENDING" && <button type="button" className="btn" disabled={busy} onClick={() => void saveDevice()}>Simpan draft perangkat</button>}<button className="btn primary" disabled={busy}>{busy ? "Menyimpan..." : "Simpan draft"}</button></div></form></MasterDialog>;
}

function ConfigForm({ data, kind, initialPlant, onClose, onSaved }: { data: Data; kind: ConfigInput["payload"]["kind"]; initialPlant: string; onClose: () => void; onSaved: () => void }) {
  const [plantId, setPlantId] = useState(initialPlant), [process, setProcess] = useState("SC"), [itemId, setItemId] = useState(""), [outputUomId, setOutputUomId] = useState("");
  const [components, setComponents] = useState<RunInput["inputs"]>([newLine()]), [requestKey] = useState(() => crypto.randomUUID()), [busy, setBusy] = useState(false), [error, setError] = useState<ApiError | null>(null);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(null);
    let payload: ConfigInput["payload"];
    if (kind === "ASSET") payload = { kind, name: String(form.get("assetName")), identity: String(form.get("identity")), ownership: String(form.get("ownership")), payer: String(form.get("payer")), costResponsibility: String(form.get("costResponsibility")), contract: String(form.get("contract")), eligibleProduction: form.get("eligible") === "YES" };
    else if (kind === "MIX") payload = { kind, process: process as "SC", outputItemId: itemId, outputUomId, components: components.map(({ locationId: _, ...line }) => line) };
    else payload = kind === "PRODUCT" ? { kind, itemId, process: process as "SC" } : { kind, itemId };
    try { await requestJson("/api/operations/configs", { requestKey, plantId, code: form.get("code"), revision: Number(form.get("revision")), effectiveFrom: `${form.get("effectiveFrom")}:00+07:00`, evidence: form.get("configEvidence"), payload }); onSaved(); } catch (caught) { setError(errorValue(caught)); } finally { setBusy(false); }
  }
  return <MasterDialog title={`Konfigurasi ${kind} · version baru`} onClose={onClose} busy={busy}><form onSubmit={submit}><div className="card-body master-form" id="field-payload" tabIndex={-1}><ErrorNotice error={error} /><PlantField data={data} value={plantId} onChange={id => { setPlantId(id); setItemId(""); }} />
    <Field name="code" label="Kode konfigurasi"><input required minLength={2} maxLength={50} /></Field><Field name="revision" label="Nomor versi"><input type="number" min="1" required defaultValue="1" /></Field><Field name="effectiveFrom" label="Berlaku mulai WIB"><input type="datetime-local" required defaultValue={localNow()} /></Field>
    {["PRODUCT", "MIX"].includes(kind) && <Field name="process" label="Proses hasil"><select value={process} onChange={e => setProcess(e.target.value)}>{["SC", "BP", "AMP", "BLENDING"].map(p => <option key={p}>{p}</option>)}</select></Field>}
    {kind !== "ASSET" && <Field name="configItem" label={kind === "FUEL" ? "Material BBM (stok L)" : "Produk hasil"}><select required value={itemId} onChange={e => setItemId(e.target.value)}><option value="">Pilih item verified</option>{data.items.filter(i => valid(i) && i.plants.some(p => p.plantId === plantId) && (kind === "FUEL" ? i.primaryUom.code === "L" : i.kind === "PRODUCT")).map(i => <option key={i.id} value={i.id}>{i.name} / {i.primaryUom.code}</option>)}</select></Field>}
    {kind === "MIX" && <><Field name="outputUomId" label="UOM hasil pembanding"><select required value={outputUomId} onChange={e => setOutputUomId(e.target.value)}><option value="">Pilih UOM</option>{data.uoms.filter(u => ["M3", "TON"].includes(u.code)).map(u => <option key={u.id} value={u.id}>{u.code}</option>)}</select></Field><MaterialRows data={data} plantId={plantId} rows={components} onChange={setComponents} title="Design per 1 UOM hasil" locations={false} /></>}
    {kind === "ASSET" && <>{[["assetName", "Nama alat / kendaraan"], ["identity", "Identitas / serial / plate terverifikasi"], ["ownership", "Ownership"], ["payer", "Payer"], ["costResponsibility", "Tanggung jawab biaya"], ["contract", "Kontrak / bukti ownership"]].map(([name, label]) => <Field key={name} name={name} label={label}><input required minLength={3} maxLength={150} /></Field>)}<Field name="eligible" label="Inclusion KPI produksi"><select required defaultValue=""><option value="">Pilih aturan dengan bukti</option><option value="YES">Eligible bila purpose produksi</option><option value="NO">Dikecualikan dengan alasan/bukti</option></select></Field></>}
    <Field name="configEvidence" label="Bukti parameter / alasan inclusion"><textarea required minLength={5} maxLength={1000} /></Field>
  </div><div className="master-actions"><button type="button" className="btn" disabled={busy} onClick={onClose}>Batal</button><button className="btn primary" disabled={busy}>{busy ? "Menyimpan..." : "Ajukan version"}</button></div></form></MasterDialog>;
}
function Decision({ value, onClose, onSaved }: { value: { run?: Run; config?: Config; action: string }; onClose: () => void; onSaved: () => void }) {
  const [busy, setBusy] = useState(false), [error, setError] = useState<ApiError | null>(null);
  return <MasterDialog title={`${value.action} · ${value.run?.number ?? value.config?.code}`} busy={busy} onClose={onClose}><form onSubmit={async e => { e.preventDefault(); const reason = new FormData(e.currentTarget).get("decisionReason"); setBusy(true); setError(null); try { await requestJson(value.config ? `/api/operations/configs/${value.config.id}` : `/api/operations/runs/${value.run!.id}`, value.config ? { evidence: reason } : { action: value.action, version: value.run!.version, reason }); onSaved(); } catch (caught) { setError(errorValue(caught)); } finally { setBusy(false); } }}><div className="card-body master-form" id="field-payload" tabIndex={-1}><ErrorNotice error={error} /><Field name="decisionReason" label="Alasan / bukti pemeriksaan"><textarea required minLength={5} maxLength={1000} /></Field></div><div className="master-actions"><button type="button" className="btn" disabled={busy} onClick={onClose}>Batal</button><button className="btn primary" disabled={busy}>{busy ? "Memproses..." : "Konfirmasi tindakan"}</button></div></form></MasterDialog>;
}
