"use client";
import { useState } from "react";
import { ApiError, ErrorNotice, Field, MasterDialog, errorValue, requestJson } from "./master-fields";
import { Files, Input, Select, get, iso, local, now } from "./stage2-fields";
import type { StageData, RecordRow, Exam, Finding } from "./stage2-workspace";
import type { InspectionInput } from "@/features/stage2/schema";
import { inspectionDraftSchema } from "@/features/stage2/offline-schema";
import { LocalDraft, saveLocalDraft, syncLocalDraft, forkLocalDraft, removeLocalDraft } from "@/lib/offline-drafts";
const workers = (data: StageData, plant: string) => data.configs.filter(c => c.kind === "WORKER" && c.status === "VERIFIED" && c.plantId === plant && c.payload.kind === "WORKER" && c.payload.active).filter((c, i, a) => a.findIndex(v => v.rootId === c.rootId) === i).map(c => ({ id: c.rootId, name: c.payload.kind === "WORKER" ? c.payload.name : c.code }));
export function InspectionEditor({ data, plantId, ownerId, row, draft, onClose, onSaved }: { data: StageData; plantId: string; ownerId: string; row?: RecordRow; draft?: LocalDraft<InspectionInput>; onClose: () => void; onSaved: () => void }) {
  const p = draft?.payload ?? (row?.payload.kind === "INSPECTION" ? row.payload : undefined);
  const [scope, setScope] = useState(p?.plantId ?? plantId), [configId, setConfig] = useState(p?.configId ?? ""), [files, setFiles] = useState(p?.fileIds ?? []), [results, setResults] = useState(p?.results ?? []), [findings, setFindings] = useState(p?.findings ?? []);
  const [busy, setBusy] = useState(false), [error, setError] = useState<ApiError | null>(null), [requestKey] = useState(p?.requestKey ?? (() => crypto.randomUUID()));
  const config = data.configs.find(c => c.id === configId), checks = config?.payload.kind === "CHECKLIST" ? config.payload.checks : [];
  const build = (f: FormData): InspectionInput => inspectionDraftSchema.parse({ kind: "INSPECTION", requestKey, plantId: scope, configId, effectiveAt: iso(get(f, "effectiveAt")), inspectorId: get(f, "inspectorId"), locationId: get(f, "locationId"), notes: get(f, "notes"), fileIds: files, results, findings });
  async function save(form: HTMLFormElement, device: boolean) { setBusy(true); setError(null); try { const payload = build(new FormData(form)); if (device) await saveLocalDraft(ownerId, payload, row ? { id: row.id, version: row.version } : undefined, draft?.revision); else { const sourceId = draft?.sourceId ?? row?.id; await requestJson(`/api/stage2/records${sourceId ? `/${sourceId}` : ""}`, { payload, version: draft?.version ?? row?.version ?? 0 }, sourceId ? "PATCH" : "POST"); } onSaved(); } catch (e) { setError(errorValue(e)); } finally { setBusy(false); } }
  return <MasterDialog title="Checklist inspeksi lapangan" busy={busy} onClose={onClose}><form onSubmit={e => { e.preventDefault(); void save(e.currentTarget, false); }}><div className="card-body"><ErrorNotice error={error} /><div className="master-form-grid"><Field name="plantId" label="Plant"><select required value={scope} disabled={!!row || !!draft} onChange={e => { setScope(e.target.value); setConfig(""); setResults([]); setFindings([]); setFiles([]); }}><option value="">Pilih...</option>{data.plants.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field name="configId" label="Versi checklist verified"><select required value={configId} onChange={e => { setConfig(e.target.value); const c = data.configs.find(c => c.id === e.target.value); setResults(c?.payload.kind === "CHECKLIST" ? c.payload.checks.map(c => ({ key: c.key, result: "NA", detail: "" })) : []); setFindings([]); }}><option value="">Pilih...</option>{data.configs.filter(c => c.kind === "CHECKLIST" && c.status === "VERIFIED" && c.plantId === scope).map(c => <option key={c.id} value={c.id}>{c.code} / v{c.revision}</option>)}</select></Field><Select name="locationId" label="Lokasi aktual" value={p?.locationId} options={data.locations.filter(l => l.plantId === scope)} /><Select name="inspectorId" label="Pemeriksa" value={p?.inspectorId} options={workers(data, scope)} /><Input name="effectiveAt" label="Waktu aktual WIB" type="datetime-local" value={p ? local(p.effectiveAt) : now()} /></div>
    {checks.map(check => { const r = results.find(r => r.key === check.key), f = findings.find(f => f.key === check.key); return <fieldset className="stage-check" key={check.key}><legend>{check.label}</legend><div className="master-form-grid"><Field name={`result-${check.key}`} label="Hasil aktual"><select value={r?.result ?? "NA"} onChange={e => { const result = e.target.value as "PASS"; setResults(results.map(r => r.key === check.key ? { ...r, result } : r)); if (result === ("FAIL" as string)) setFindings([...findings.filter(f => f.key !== check.key), { key: check.key, detail: "", severity: "MEDIUM", picId: "", dueDate: "", fileIds: [] }]); else setFindings(findings.filter(f => f.key !== check.key)); }}><option>PASS</option><option>FAIL</option><option>NA</option></select></Field><Field name={`detail-${check.key}`} label="Observasi"><input value={r?.detail ?? ""} onChange={e => setResults(results.map(r => r.key === check.key ? { ...r, detail: e.target.value } : r))} /></Field></div>{f && <div className="master-form-grid"><Field name={`finding-${check.key}`} label="Temuan aktual"><textarea required minLength={5} value={f.detail} onChange={e => setFindings(findings.map(f => f.key === check.key ? { ...f, detail: e.target.value } : f))} /></Field><Field name={`severity-${check.key}`} label="Severity"><select value={f.severity} onChange={e => setFindings(findings.map(f => f.key === check.key ? { ...f, severity: e.target.value as "HIGH" } : f))}>{["LOW", "MEDIUM", "HIGH"].map(v => <option key={v}>{v}</option>)}</select></Field><Field name={`pic-${check.key}`} label="PIC follow-up"><select required value={f.picId} onChange={e => setFindings(findings.map(f => f.key === check.key ? { ...f, picId: e.target.value } : f))}><option value="">Pilih...</option>{workers(data, scope).map(w => <option key={w.id} value={w.id}>{w.name}</option>)}</select></Field><Field name={`due-${check.key}`} label="Target selesai"><input required type="date" value={f.dueDate} onChange={e => setFindings(findings.map(f => f.key === check.key ? { ...f, dueDate: e.target.value } : f))} /></Field><Files domain="INSPECTION" plantId={scope} value={f.fileIds} onChange={ids => setFindings(findings.map(f => f.key === check.key ? { ...f, fileIds: ids } : f))} /></div>}</fieldset>; })}
    <Field name="notes" label="Catatan inspeksi"><textarea name="notes" rows={3} minLength={5} required defaultValue={p?.notes} /></Field><Files domain="INSPECTION" plantId={scope} value={files} onChange={setFiles} /></div><div className="master-actions"><button className="btn" type="button" disabled={busy} onClick={e => { const form = e.currentTarget.form; if (form?.reportValidity()) void save(form, true); }}>Simpan di perangkat</button><button className="btn primary" disabled={busy}>Simpan draft server</button></div></form></MasterDialog>;
}
export function DeviceDrafts({ drafts, data, onEdit, onRefresh }: { drafts: LocalDraft<InspectionInput>[]; data: StageData; onEdit: (d: LocalDraft<InspectionInput>) => void; onRefresh: () => Promise<void> }) {
  const [busy, setBusy] = useState(false), [error, setError] = useState<ApiError | null>(null), [compare, setCompare] = useState<LocalDraft<InspectionInput> | null>(null);
  const work = async (fn: () => Promise<void>) => { setBusy(true); setError(null); try { await fn(); await onRefresh(); } catch (e) { setError(errorValue(e)); } finally { setBusy(false); } };
  const server = compare ? data.records.find(r => r.id === compare.sourceId || r.payload.requestKey === compare.id) : undefined;
  return <section className="card"><div className="card-head"><h2>Draft inspeksi perangkat</h2><small>UUID tetap / konflik ditampilkan</small></div><div className="stage-stack"><ErrorNotice error={error} />{drafts.map(d => <article className="stage-row" key={d.id}><strong>{d.payload.effectiveAt.slice(0, 10)} · {d.id.slice(0, 8)}</strong><span>{d.state} · revisi perangkat {d.revision} / server {d.version}</span>{d.error && <p role="alert">{d.error}</p>}<div className="stage-actions"><button className="btn" disabled={busy} onClick={() => onEdit(d)}>Edit</button><button className="btn" disabled={busy || d.state === "SYNCED"} onClick={() => void work(() => syncLocalDraft(d))}>Sync</button><button className="btn" onClick={() => setCompare(d)}>Bandingkan</button><button className="btn" disabled={busy} onClick={() => void work(() => forkLocalDraft(d))}>Salinan baru</button><button className="btn" disabled={busy} onClick={() => void work(() => removeLocalDraft(d))}>Hapus perangkat</button></div></article>)}{!drafts.length && <p className="muted">Belum ada draft perangkat.</p>}</div>{compare && <MasterDialog title="Bandingkan draft perangkat dan server" onClose={() => setCompare(null)}><div className="card-body stage-compare"><section><h3>Perangkat / v{compare.version}</h3><p>{compare.payload.notes}</p>{compare.payload.results.map(r => <p key={r.key}>{r.key}: {r.result} / {r.detail}</p>)}</section><section><h3>Server / v{server?.version ?? "N/A"}</h3>{server?.payload.kind === "INSPECTION" ? <><p>{server.payload.notes}</p>{server.payload.results.map(r => <p key={r.key}>{r.key}: {r.result} / {r.detail}</p>)}</> : <p>Hubungkan dan pilih periode sumber untuk memuat versi server.</p>}</section></div></MasterDialog>}</section>;
}
export function ExamEditor({ data, plantId, row, onClose, onSaved }: { data: StageData; plantId: string; row?: Exam; onClose: () => void; onSaved: () => void }) {
  const [scope, setScope] = useState(row?.plantId ?? plantId), [measurements, setMeasurements] = useState(row?.measurements ?? [{ label: "", value: "", unit: "" }]), [files, setFiles] = useState(row?.fileIds ?? []), [requestKey] = useState(row?.requestKey ?? (() => crypto.randomUUID())), [busy, setBusy] = useState(false), [error, setError] = useState<ApiError | null>(null);
  return <MasterDialog title="Pemeriksaan berizin WCU / DCU" busy={busy} onClose={onClose}><form onSubmit={async e => { e.preventDefault(); setBusy(true); setError(null); try { const f = new FormData(e.currentTarget); await requestJson(`/api/stage2/exams${row ? `/${row.id}` : ""}`, { version: row?.version ?? 0, payload: { requestKey, plantId: scope, workerId: get(f, "workerId"), kind: get(f, "kind"), examAt: iso(get(f, "examAt")), validUntil: iso(get(f, "validUntil")), workStatus: get(f, "workStatus"), notes: get(f, "notes"), measurements, fileIds: files } }, row ? "PATCH" : "POST"); onSaved(); } catch (e) { setError(errorValue(e)); } finally { setBusy(false); } }}><div className="card-body"><ErrorNotice error={error} /><div className="master-form-grid"><Field name="plantId" label="Plant"><select required value={scope} disabled={!!row} onChange={e => { setScope(e.target.value); setFiles([]); }}><option value="">Pilih...</option>{data.plants.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Select name="workerId" label="Pekerja" value={row?.workerId} options={workers(data, scope)} /><Select name="kind" label="Jenis pemeriksaan" value={row?.kind} options={["WCU", "DCU"].map(v => ({ id: v, name: v }))} /><Input name="examAt" label="Waktu pemeriksaan WIB" type="datetime-local" value={row ? local(row.examAt) : now()} /><Input name="validUntil" label="Berlaku sampai WIB" type="datetime-local" value={row ? local(row.validUntil) : ""} /><Select name="workStatus" label="Kesimpulan pemeriksa" value={row?.workStatus} options={["FIT", "RESTRICTED", "UNFIT", "PENDING"].map(v => ({ id: v, name: v }))} /></div><fieldset><legend>Pengukuran aktual</legend>{measurements.map((m, i) => <div className="stage-measurement" key={i}>{["label", "value", "unit"].map(k => <Field key={k} name={`${k}-${i}`} label={({ label: "Pemeriksaan", value: "Nilai aktual", unit: "Unit" } as Record<string, string>)[k]}><input required={k !== "unit"} value={m[k as keyof typeof m]} onChange={e => setMeasurements(measurements.map((v, n) => n === i ? { ...v, [k]: e.target.value } : v))} /></Field>)}<button className="btn" type="button" disabled={measurements.length === 1} onClick={() => setMeasurements(measurements.filter((_, n) => n !== i))}>Hapus</button></div>)}<button className="btn" type="button" onClick={() => setMeasurements([...measurements, { label: "", value: "", unit: "" }])}>Tambah pengukuran</button></fieldset><Field name="notes" label="Catatan pemeriksa (akses medis terbatas)"><textarea name="notes" rows={4} minLength={5} required defaultValue={row?.notes} /></Field><Files domain="MEDICAL" plantId={scope} value={files} onChange={setFiles} /></div><div className="master-actions"><button className="btn primary" disabled={busy}>Simpan draft pemeriksaan</button></div></form></MasterDialog>;
}
export function FollowupEditor({ finding, onClose, onSaved }: { finding: Finding; onClose: () => void; onSaved: () => void }) {
  const [files, setFiles] = useState<string[]>([]), [requestKey] = useState(() => crypto.randomUUID()), [busy, setBusy] = useState(false), [error, setError] = useState<ApiError | null>(null);
  return <MasterDialog title={`Follow-up / ${finding.key}`} busy={busy} onClose={onClose}><form onSubmit={async e => { e.preventDefault(); setBusy(true); setError(null); try { const f = new FormData(e.currentTarget); await requestJson("/api/stage2/followups", { requestKey, findingId: finding.id, actualAt: iso(get(f, "actualAt")), note: get(f, "note"), fileIds: files }); onSaved(); } catch (e) { setError(errorValue(e)); } finally { setBusy(false); } }}><div className="card-body"><ErrorNotice error={error} /><p>{finding.detail}</p><Input name="actualAt" label="Waktu tindak lanjut WIB" type="datetime-local" value={now()} /><Field name="note" label="Tindakan / hasil aktual"><textarea name="note" required minLength={5} rows={5} /></Field><Files domain="INSPECTION" plantId={finding.plantId} value={files} onChange={setFiles} /><p className="muted">Temuan tetap OPEN sampai verifikasi akun terpisah.</p></div><div className="master-actions"><button className="btn primary" disabled={busy}>Submit follow-up</button></div></form></MasterDialog>;
}
