"use client";
import { useState } from "react";
import { Field, MasterDialog, ApiError, ErrorNotice, errorValue, requestJson } from "./master-fields";
import type { ConfigInput } from "@/features/stage2/schema";
export type StageConfig = { id: string; rootId: string; subjectId: string | null; plantId: string; kind: string; code: string; revision: number; effectiveFrom: string; status: string; makerId: string; attestedBy: string | null; verifiedBy: string | null; payload: ConfigInput["payload"]; evidence: string };
export type Plant = { id: string; code: string; name: string; verificationStatus: string };
export const now = () => new Date(Date.now() + 7 * 3600000).toISOString().slice(0, 16);
export const iso = (v: string) => new Date(`${v}${v.length === 10 ? "T00:00" : ""}:00+07:00`).toISOString();
export const local = (v: string) => new Date(new Date(v).getTime() + 7 * 3600000).toISOString().slice(0, 16);
export const get = (f: FormData, k: string) => String(f.get(k) ?? "");
export const status = (v: string) => <span className={`badge ${["VERIFIED", "ISSUED", "POSTED", "RESOLVED"].includes(v) ? "green" : "amber"}`}>{v}</span>;
export function Input({ name, label, value = "", type = "text", required = true }: { name: string; label: string; value?: string | number; type?: string; required?: boolean }) { return <Field name={name} label={label}><input name={name} type={type} defaultValue={value} required={required} step={type === "number" ? "any" : undefined} /></Field>; }
export function Select({ name, label, options, value = "", required = true }: { name: string; label: string; options: { id: string; name: string }[]; value?: string; required?: boolean }) { return <Field name={name} label={label}><select name={name} defaultValue={value} required={required}><option value="">Pilih...</option>{options.map(o => <option key={o.id} value={o.id}>{o.name}</option>)}</select></Field>; }
export function Files({ plantId, domain, value, onChange }: { plantId: string; domain: string; value: string[]; onChange: (v: string[]) => void }) {
  const [busy, setBusy] = useState(false), [error, setError] = useState<ApiError | null>(null);
  return <div className="stage-evidence"><label>Bukti / foto (PDF, JPEG, PNG, WebP; maks. 4 MiB)<input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" disabled={busy || !plantId} onChange={async e => {
    const file = e.currentTarget.files?.[0], input = e.currentTarget; if (!file) return; setBusy(true); setError(null);
    try { if (file.size > 4 * 1024 * 1024 || !navigator.onLine) throw new ApiError("Unggah bukti memerlukan koneksi dan ukuran maksimal 4 MiB."); const url = `/api/stage2/files?${new URLSearchParams({ requestKey: crypto.randomUUID(), plantId, domain, name: file.name })}`, response = await fetch(url, { method: "POST", headers: { "Content-Type": file.type }, body: file }); const result = await response.json(); if (!response.ok) throw new ApiError(result.message); onChange([...value, result.data.id]); input.value = ""; } catch (e) { setError(errorValue(e)); } finally { setBusy(false); }
  }} /></label><ErrorNotice error={error} /><ul>{value.map(id => <li key={id}><a href={`/api/stage2/files/${id}`} target="_blank" rel="noreferrer">Bukti {id.slice(0, 8)}</a><button className="btn" type="button" onClick={() => onChange(value.filter(v => v !== id))}>Lepas</button></li>)}</ul></div>;
}
const options = (values: string[]) => values.map(v => ({ id: v, name: v }));
export function ConfigEditor({ kind, configs, plants, plantId, previous, onClose, onSaved }: { kind: ConfigInput["payload"]["kind"]; configs: StageConfig[]; plants: Plant[]; plantId: string; previous?: StageConfig; onClose: () => void; onSaved: () => void }) {
  const [busy, setBusy] = useState(false), [error, setError] = useState<ApiError | null>(null), [requestKey] = useState(() => crypto.randomUUID());
  const [scope, setScope] = useState(previous?.plantId ?? plantId);
  const old = previous?.payload;
  const [fileIds, setFileIds] = useState(old?.kind === "ASSET" ? old.fileIds : []);
  const v = (key: string, fallback: string | number = "") => String(old && key in old ? (old as unknown as Record<string, unknown>)[key] : fallback);
  const field = (key: string, label: string, type = "text", required = true) => <Input name={key} label={label} type={type} value={v(key)} required={required} />;
  const choice = (key: string, label: string, values: string[]) => <Select name={key} label={label} value={v(key)} options={options(values)} />;
  return <MasterDialog title={`Parameter ${kind}${previous ? ` / revisi ${previous.revision + 1}` : ""}`} busy={busy} onClose={onClose}><form onSubmit={async event => {
    event.preventDefault(); const f = new FormData(event.currentTarget), s = (k: string) => get(f, k), n = (k: string) => Number(s(k)); setBusy(true); setError(null);
    try {
      let payload: ConfigInput["payload"];
      if (kind === "LETTER_TYPE") payload = { kind, name: s("name"), displayCode: s("displayCode"), aliases: s("aliases").split(",").map(v => v.trim()).filter(Boolean), format: s("format"), scope: s("scope") as "GLOBAL", reset: s("reset") as "YEAR", padding: n("padding"), start: n("start"), approvalRequired: f.has("approvalRequired") };
      else if (kind === "ASSET") payload = { kind, name: s("name"), identity: s("identity"), plate: s("plate"), serial: s("serial"), chassis: s("chassis"), model: s("model"), ownership: s("ownership") as "OWNED", unitCount: n("unitCount"), ownershipEvidence: s("ownershipEvidence"), fileIds, ...Object.fromEntries(["legacyEquipmentId", "operationalAssetId", "vehicleId"].flatMap(k => s(k) ? [[k, s(k)]] : [])) };
      else if (kind === "ASSET_FINANCE") payload = { kind, assetId: s("assetId"), cost: s("cost"), residual: s("residual"), lifeMonths: n("lifeMonths"), startDate: s("startDate"), firstMonth: s("firstMonth") as "FULL", openingMonth: s("openingMonth"), openingAccumulated: s("openingAccumulated"), currency: s("currency"), decimals: n("decimals") };
      else if (kind === "WORKER") payload = { kind, name: s("name"), job: s("job"), employment: s("employment"), active: f.has("active"), ...(s("userId") ? { userId: s("userId") } : {}) };
      else payload = { kind, name: s("name"), checks: s("checks").split("\n").filter(v => v.trim()).map(v => { const [key, ...label] = v.split("|"); return { key: key.trim(), label: label.join("|").trim() }; }) };
      await requestJson("/api/stage2/configs", { requestKey, plantId: s("plantId"), code: s("code"), revision: previous ? previous.revision + 1 : 1, effectiveFrom: iso(s("effectiveFrom")), evidence: s("evidence"), payload }); onSaved();
    } catch (e) { setError(errorValue(e)); } finally { setBusy(false); }
  }}><div className="card-body"><ErrorNotice error={error} /><div className="master-form-grid"><Field name="plantId" label="Plant"><select name="plantId" required value={scope} onChange={e => { setScope(e.target.value); setFileIds([]); }}><option value="">Pilih...</option>{plants.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Input name="code" label="Kode stabil" value={previous?.code ?? ""} /><Input name="effectiveFrom" label="Efektif sejak (WIB)" type="datetime-local" value={now()} /></div>
    <div className="master-form-grid">{kind !== "ASSET_FINANCE" && field("name", "Nama")}
      {kind === "LETTER_TYPE" && <>{field("displayCode", "Kode surat verified")}{field("format", "Format nomor: {seq}/{code}/{year}/{month}/{plant}")}{choice("scope", "Cakupan deret", ["GLOBAL", "TYPE", "PLANT_TYPE"])}{choice("reset", "Reset deret", ["YEAR", "MONTH", "NEVER"])}{field("padding", "Digit nomor", "number")}{field("start", "Nomor awal", "number")}<Input name="aliases" label="Alias, pisahkan koma" value={old?.kind === "LETTER_TYPE" ? old.aliases.join(", ") : ""} required={false} /><label><input type="checkbox" name="approvalRequired" defaultChecked={old?.kind === "LETTER_TYPE" && old.approvalRequired} /> Persetujuan Manager sebelum issue</label></>}
      {kind === "ASSET" && <>{field("identity", "Identitas alat stabil")}{field("plate", "Plat", "text", false)}{field("serial", "Serial", "text", false)}{field("chassis", "Chassis", "text", false)}{field("model", "Model")}{choice("ownership", "Kepemilikan", ["OWNED", "RENTED"])}{field("unitCount", "Jumlah unit fisik", "number")}{field("legacyEquipmentId", "ID equipment sumber (opsional)", "text", false)}{field("operationalAssetId", "ID versi alat BBM verified (opsional)", "text", false)}{field("vehicleId", "ID versi kendaraan verified (opsional)", "text", false)}{field("ownershipEvidence", "Bukti kepemilikan / kontrak / STNK")}</>}
      {kind === "ASSET_FINANCE" && <><Select name="assetId" label="Aset owned verified" value={v("assetId")} options={configs.filter(c => c.kind === "ASSET" && c.status === "VERIFIED" && (c.payload as { ownership: string }).ownership === "OWNED").filter((c, i, a) => a.findIndex(v => v.rootId === c.rootId) === i).map(c => ({ id: c.rootId, name: `${c.code} - ${(c.payload as { name: string }).name}` }))} />{field("cost", "Harga perolehan", "number")}{field("residual", "Nilai residu", "number")}{field("lifeMonths", "Umur manfaat (bulan)", "number")}{field("startDate", "Tanggal mulai", "date")}{choice("firstMonth", "Perlakuan bulan pertama", ["FULL", "NEXT_MONTH", "DAILY_ACTUAL"])}{field("openingMonth", "Bulan pertama ledger / cutoff", "month")}{field("openingAccumulated", "Akumulasi sebelum cutoff", "number")}{field("currency", "Mata uang ISO")}{field("decimals", "Presisi pembulatan HALF_UP", "number")}</>}
      {kind === "WORKER" && <>{field("job", "Jabatan / tugas")}{field("employment", "Hubungan kerja")}{field("userId", "ID akun PIC (opsional)", "text", false)}<label><input type="checkbox" name="active" defaultChecked={old?.kind === "WORKER" ? old.active : true} /> Aktif</label></>}
    </div>{kind === "CHECKLIST" && <Field name="checks" label="Checklist: satu key | pertanyaan per baris"><textarea name="checks" required rows={8} defaultValue={old?.kind === "CHECKLIST" ? old.checks.map(c => `${c.key} | ${c.label}`).join("\n") : ""} /></Field>}
    {kind === "ASSET" && <Files domain="ASSET" plantId={scope} value={fileIds} onChange={setFileIds} />}<Field name="evidence" label="Acuan dan bukti parameter"><textarea name="evidence" required minLength={5} rows={3} /></Field><p className="muted">Aktivasi menunggu verifikasi akun terpisah. Parameter perusahaan diisi dari bukti yang disahkan.</p></div><div className="master-actions"><button type="button" className="btn" onClick={onClose} disabled={busy}>Batal</button><button className="btn primary" disabled={busy}>Simpan versi draft</button></div></form></MasterDialog>;
}
